packages/contract/src/EphemeralNotes.sol, packages/contract/test/EphemeralNotes.t.sol
On-chain, anyone who can show up with a signature of their address from the ephemeral (regular ECDSA) keypair can claim the note. Separately, the sender themselves can always claim the note (even without a signature), that way the sender can sweep old notes even if they lose the private keys themselves.
Off-chain, the expected flow is that the sender will send the private key (as part of the temp URL) to the receiver.
=> Ephemeral Notes contract

.vscode/settings.json, README.md, apps/daimo-mobile/babel.config.js, apps/daimo-mobile/eas.json, apps/daimo-mobile/package.json, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/logic/env.ts, apps/daimo-mobile/src/view/screen/UserScreen.tsx, package-lock.json, package.json, packages/daimo-api/src/index.ts, packages/daimo-contract/package.json
- Quick start instructions in README
- Certain env vars inlined into compiled app. See `env.ts`
- API URL no longer hardcoded. `DAIMO_APP_API_URL` still defaults to `locahost:3000`
- You can point it to `https://daimo-api-stage.onrender.com` to use deployed staging API
=> Dev quick start, use remote API

apps/daimo-mobile/src/debugLog.ts, apps/daimo-mobile/test/log.test.ts
Now supports console.`log`/`warn`/`error`
- Includes error stacktrace, if available
- Truncates very long lines
- Added unit test
=> Debug log test

apps/daimo-mobile/app.json, apps/daimo-mobile/src/sync/recipients.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ClaimNoteScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/send/CreateNoteTab.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/Input.tsx
- Allow Notifications during onboarding > automatically register push token later, once account exists
- make the app feel faster
- show pending op right after onboarding, on faucet request
- show pending op for Create Note
- show pending op for Claim Note
=> fix: onboarding Allow Notifications, pending op for faucet & notes

apps/daimo-web/public/.well-known/assetlinks.json
assetslinks.json is necessary for android app links to work out of the box
=> Add assetlinks for android

apps/daimo-web/next.config.js
Fixes our instance of https://github.com/depcheck/depcheck/issues/812, I don't like that we have to change our code to make our linter tooling work correctly in general.
Before:
After:
=> Fix depcheck Next config fail

apps/daimo-mobile/src/logic/note.ts, apps/daimo-mobile/src/view/HomeStack.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/receive/CreateRequestScreen.tsx, apps/daimo-mobile/src/view/screen/receive/SendRequestScreen.tsx, apps/daimo-mobile/src/view/shared/Header.tsx, apps/daimo-mobile/src/view/shared/nav.ts, packages/daimo-api/src/router.ts, packages/daimo-common/src/daimoLink.ts
=> refactor: inbound link screens, starting with NoteScreen

apps/daimo-mobile/src/action/actStatus.ts, apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/CreateNoteTab.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/Amount.tsx, apps/daimo-mobile/src/view/shared/Input.tsx, packages/daimo-api/src/contract/nameRegistry.ts
=> fix: send, cleaner useSendAsync, note > payment link

package-lock.json, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/BiometricsKeyManager.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/FallbackKeyManager.kt, packages/daimo-expo-enclave/package.json, packages/daimo-expo-enclave/src/index.ts
Unclear why #191 happens since we're explicitly catching those throws (possible @dcposch had an old module build somehow?), this PR should clean up that throw logic anyway.
=> expo-enclave: Don't throw on failed reads

packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/ExpoEnclaveModule.kt
Closes #193, tested on simulator API 29.
=> fix: Android 28 to 30 don't have getSecurityLevel

packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/router.ts
Tested request tracking still works:
Closes #210
=> fix: stop assuming that one tx has one userop

apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/components/AppStoreBadge.tsx
- deep links only redirect post-onboarding now instead of crashing like before
- app store badge on web detects platform
Closes some of the tasks in #118
=> minor deep link flow improvements

apps/daimo-mobile/src/model/account.ts, packages/daimo-expo-enclave/ios/FallbackKeyManager.swift, packages/daimo-expo-enclave/ios/GenericPasswordStore.swift, packages/daimo-expo-enclave/ios/SecureEnclaveKeyManager.swift
Veridise Audit ID 9
Tested on few different iOS configurations:
- Face ID enabled, secure enclave
- iOS Simulator, software keys
- Face ID enabled, Secure Enclave forcefully disabled so using Fallback settings (by hardcoding `shouldUseSecureEnclave` in swift expo-enclave module)
=> Add user presence access control to fallback key manager keychain auth

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/receive/CreateRequestScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/Amount.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/Header.tsx, apps/daimo-mobile/src/view/shared/InfoLink.tsx, apps/daimo-mobile/src/view/shared/InputBig.tsx, apps/daimo-mobile/src/view/shared/ScrollPellet.tsx, apps/daimo-mobile/src/view/shared/style.ts, apps/daimo-mobile/src/view/shared/text.tsx
match @daimo/web colors
use `<SafeAreaView/>` to pad the header properly
=> fix: header spacing, colors

apps/daimo-mobile/src/view/screen/send/CancelHeader.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/test/nav.test.ts
we currently show just the recipient, not a prefilled dollar amount
We can discuss integration test strategy for a future PR. I'd love to get something like to the release test checklist automated (though we'd still run through it manually, ofc, for production releases).
=> fix: handle request link

apps/daimo-web/src/app/[...topLevelPage]/route.tsx
super.so killed our notion bridge because we pointed daimo.xyz to a different DNS sigh
would recommend pushing to prod asap, this is killing our blog and privacy page etc. ATM
=> web: Fix super.so domain

apps/daimo-web/src/app/[...topLevelPage]/route.tsx
Before, we were proxying to `cname.super.so` which may have rate limited or otherwise blocked us.
Fixed by changing to `daimo.super.site`. Different IP:
```
dc-mbp-m2:daimo-mobile dc$ nslookup cname.super.so
Server:         192.168.1.1
Address:        192.168.1.1#53
Non-authoritative answer:
cname.super.so  canonical name = cname.vercel-dns.com.
Name:   cname.vercel-dns.com
Address: 76.76.21.22
Name:   cname.vercel-dns.com
Address: 76.76.21.9
dc-mbp-m2:daimo-mobile dc$ nslookup daimo.super.site
Server:         192.168.1.1
Address:        192.168.1.1#53
Non-authoritative answer:
Name:   daimo.super.site
Address: 76.76.21.123
Name:   daimo.super.site
Address: 76.76.21.164
```
=> @daimo/web: fix Notion proxy

apps/daimo-mobile/eas.json, apps/daimo-mobile/src/action/useSendAsync.ts, apps/scratchpad/src/createAccount.ts, apps/scratchpad/src/index.ts, packages/daimo-api/src/chain/bundlerClient.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts, packages/daimo-api/src/trpc.ts, packages/daimo-common/src/model.ts, packages/daimo-userop/src/callback.ts, packages/daimo-userop/src/daimoOpBuilder.ts, packages/daimo-userop/src/daimoOpSender.ts, packages/daimo-userop/src/index.ts, packages/daimo-userop/src/signingCallback.ts
- Hide Pimlico API key, which is not meant for client distribution
- Track transaction reliability and performance
- Simplify configuration. Daimo app only uses a single API endpoint now, which makes it feasible to make this user-configurable like the RPC endpoint in traditional eth wallets, in the future.
=> sendUserOp via API

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/OnrampCBPay.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/cron.ts, packages/daimo-common/src/daimoLink.ts
mainnet testing todos:
- Closes #233 
- stopgap reduce regular sync time from 30 secs to 10
=> Release bug fixes

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/OnrampCBPay.tsx
We can't use SafeAreaView because it has a bug:  https://github.com/software-mansion/react-native-screens/issues/1276
Using insets with padding a regular view seems to work.
=> workaround safe area view flicker bug

apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, packages/daimo-api/src/env.ts, packages/daimo-api/src/pushNotifier.ts, packages/daimo-api/src/router.ts, packages/daimo-api/test/pushNotifier.test.ts
On local dev, before entering the full string "testnet" it will say "Offline?" since we don't run an API server with chainID 8453 but I think that's fine since it only affects us internally.
Also fix capitalisation bug in key rotation push notifier.
=> Move invite codes to be server-side

packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/env.ts
Fixes the edge case where two `deployWallet` race and one fails due to bad nonce.
Verified fix by running create account simultaneously on sim and dev build:
Closes #382
=> Retry backoff on wallet deploy tx

apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx
Tested on sim.
In future we should take a pass at typing OpEvents better to prevent these.
This PR assumes no transfer page needs to be updated / can never be pending if it does not have an OpHash.
=> Fix history op wrongly syncing

apps/daimo-mobile/src/logic/trpc.tsx, apps/daimo-mobile/src/view/shared/OfflineHeader.tsx
Android "offline" label hidden behind the camera on Pixel 2. Camera apparently not included in `useSafeAreaInsets`
Android offline unreliable--`fetch()` default timeout is super long, 5 minutes in Chrome, so sync can take forever to fail
- Added manual top padding for Android
- Added fetch timeout
=> mobile: fix Android offline state, add fetch timeout

apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/QRScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/shared/AccountBubble.tsx, apps/daimo-mobile/src/view/shared/ButtonCircle.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-web/src/components/PerformWalletAction.tsx
Handful of improvements/fixes:
- Make "Explorer" generic instead of Basescan
- QR Flow improvements
- Add a share button on "Pay me"
- <img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/98b8dec3-12ea-4257-b59c-d7e373886bdf">
- Add button to search results on send
- <img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/0e1a712f-bbac-4895-8681-1afb0cd703eb"> <img width="256" src="https://github.com/daimo-eth/daimo/assets/6984346/342695b7-4e8f-46c7-8955-69e89bb50345">
- Make send Payment link page unstick regardless of whether it is shared or not and make it consistent on Android.
- New flow: Regardless of sharing or not, we reset the send page, and redirect to home page. So you see the Pending state of the link, and then if you go back to the send …
=> Misc. improvements

apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/contract/faucet.ts, packages/daimo-api/src/cron.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/env.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts, packages/daimo-common/src/model.ts
Repurposes Faucet to auto-send for invite code accounts.
Onboarding: Moves invite page after flow selection page. So now if we have to test Use Existing flow on testnet we need to first go into create account and enter a testnet invite code, we can make this better in future but this only affects us internally for testing so doing this for now.
new flow screenshots:
Slight copy updates, "faucet" -> "team daimo", "Use existing" -> "Already have an account?"
=> API: invite codes, auto-faucet

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/logic/key.ts
saves a few cent per tx.
tested on mainnet.
before: https://basescan.org/tx/0x99596117a3f63f69cd29f36656f816b4f13370f07d77021347706a68a656868a
after: https://basescan.org/tx/0xc4fb21679d091a1ec87341a15cc141b5303c671043efdcdd1c856f31c558ae04
Thanks to Ansgar's analysis for discovering this.
=> remove origin from raw sigs to reduce calldata

packages/daimo-api/src/api/getAccountHistory.ts
From Carl Fluke at CB:
> Assets and Blockchains is an OR filter. If you remove blockchains, you should get what you are after.
=> api: fix CBPay asset filter

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx
No more warnings on home screen because no more flatlist inside scrollview.
I use reanimated to achieve exactly same result, but I don't know if I like the code more. No more angry warnings though
=> No more flatlist inside scrollview

apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendNavScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-mobile/src/view/shared/nav.ts
https://github.com/daimo-eth/daimo/assets/6984346/8f988b15-1a69-4094-bae9-0a60eab67e98
Seeing Ibbi use the app / walking through what he was thinking seems like 1) having a tab for notes but not QR is unintuitive and 2) Having a search and Send link title makes it not obvious that both the tabs are for sending and not another action.
This seems like a clean solution. Thoughts?
=> Send: no tab for links

apps/daimo-mobile/src/sync/sync.ts, packages/daimo-api/src/contract/paymaster.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/src/server/trpc.ts
Heisenbug that occurs whenever signature `r` or `s` starts with a hex 0, lovely
Fixed
=> api: add error logging, paymasterAndData sanity check

apps/daimo-mobile/src/view/shared/SuggestedActionBox.tsx
This was mainly for the debug and development reasons to reopen modal repeatedly but was probably not noticeable in release since suggestedActions go away but still should be removed I think
=> Disable dev auto reopen suggested action

packages/daimo-api/src/network/viemClient.ts
I noticed that the cached log files were organized by start and stop block. I also noticed that the start and stop blocks overlapped. For example:
```
logs-Transfer-5710000-5715000
logs-Transfer-5715000-5720000
```
I then explored these files to find the following:
```
cat logs-Transfer-5715000-5720000 | \
jq 'map(select(.blockNumber == "5715000n")) | .[0].transactionHash'
"0x71093f5b99ff2f550face2ccf3ce994cc58ce604cd62ee59bd6c0970fbb11a34"
cat  logs-Transfer-5710000-5715000 | \
jq 'map(select(.blockNumber == "5715000n")) | .[0].transactionHash'
"0x71093f5b99ff2f550face2ccf3ce994cc58ce604cd62ee59bd6c0970fbb11a34"
```
I don't think this problem exists after initialization since the tryProcessLogsToLatestBlock function uses the previous stop + 1 for the next start.
Which is what this commit …
=> daimo-api: fix duplicate during indexer init

apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/shared/AnimatedCircle.tsx, apps/daimo-mobile/src/view/shared/Button.tsx
Add long press button to confirm transaction. Animation can be customized a little (duration, size of circle and width of stroke but I can add more)
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/4cd911df-4254-442e-bdb5-5b0be50db8cc
Android
https://github.com/daimo-eth/daimo/assets/42337257/c61acbc9-ac34-44b3-bd9c-bc232fffece1
=> Add long press button to confirm transaction

packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/test/dtest.ts
Prior to this commit, and prior to shovel, the getAccountHistory function would use the ViemClient to get the latest block. This assumed that the ViemClient would be updating its block. Now that we are using Watcher, ViemClient was no longer updating its block which means that it latest value was only set on startup and then never updated.
Now you can ask Watcher for the latest block. It makes an RPC request to get the block's timestamp. Ideally this should be in the shovel table but it's not. I'm going to fix shovel so that it stores the block timestamp on the task table so that the Watcher will have the timestamp whenever it has the number.
=> daimo-api: bugfix. return latest block for getAccountHistory

packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/shovel/watcher.ts
I'm 50/50 on this change. I don't like that it adds a delay in the signup process. But it avoids hitting an error (silent?) when the user signs up and their keys have not been indexed.
The alternative is that we remove the assert and instead return some kind of empty result for getAccountHistory until the user's data has been indexed.
https://github.com/daimo-eth/daimo/blob/master/packages/daimo-api/src/api/getAccountHistory.ts#L107-L108
=> daimo-api: wait for deploy to be indexed

packages/daimo-api/src/contract/keyRegistry.ts
Prior to this commit, we were leaving the order of keys returned from key_{added,removed} undefined. I guess it worked for a while, but in testing I found that the getAccountHistory endpoint was returning invalid keys. Now that the order is defined, the contractFriendlyKeyToDER function should produce correct results.
=> daimo-api: fix account pubkey

apps/daimo-mobile/app.config.js, apps/daimo-mobile/eas.json, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, packages/daimo-api/src/shovel/watcher.ts
Allow tablets to be build and distributed for. Also fix scroll and keyboard handling when installed on Mac.
Allow resize of the window but unfortunately when scaled up it does animate in very choppy manner - I will try to fix it asap but think that it shouldn't be a blocker for whole app 
https://github.com/daimo-eth/daimo/assets/42337257/64c07144-335f-419c-a5ac-33e53cdb003b
=> Add support for tablets and resize app on Mac

packages/daimo-api/src/contract/keyRegistry.ts
Subtle ordering bug if two userops make it into the same block.
=> api: sort transaction index for key rotations within block

apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx
Just used `navResetToHome` func to go back.
Every time we use navResetToHome it blinks a little creating ugly effect that is much more visible on Android. I think we need to find some more elegant way to handle navigation reset. (Will try to investigate that now but since this is not a part of [this issue](https://github.com/daimo-eth/daimo/issues/513), it should be a separate PR)
iOS: 
https://github.com/daimo-eth/daimo/assets/42337257/eb38f0d9-0dcc-4c29-9dc0-e29c9257098e
Android:
https://github.com/daimo-eth/daimo/assets/42337257/30942acd-85ee-460a-b604-5c0ebc434798
=> Add X to go back to home from send flow

apps/daimo-mobile/src/view/shared/AnimatedSearchInput.tsx
Use onLayout to determine size of the input instead of measure inside animated style
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/a8525f2c-7f08-4765-92f6-16cbaf1cac5a
Android:
https://github.com/daimo-eth/daimo/assets/42337257/47bd95f7-1f8b-4f80-9bcd-30a5a7f70cef
=> Fix 0 width search header input

apps/daimo-mobile/app.config.js, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx
fix #545
- back button works
- clicking amount to edit again works
- `HOLD TO CONFIRM`
=> mobile: payment link Hold to Confirm

apps/daimo-mobile/src/App.tsx
Added wrapper with dynamic state-based pointerEvents prop to make sure that debug modal doesn't prevent interactions even if invisible. 
Android:
https://github.com/daimo-eth/daimo/assets/42337257/4e9ef637-ead6-4824-967c-a4a9866a4b00
iOS: 
https://github.com/daimo-eth/daimo/assets/42337257/72da12f5-c85e-457f-bd01-3be2d417a8cd
=> Add pointer events wrapper around debug modal

apps/daimo-mobile/src/view/shared/Button.tsx
I realised that it was enough to tap on long press transaction button to make it work.
Now it check if the animation was played all the way to the end before call `onPress`
iOS
https://github.com/daimo-eth/daimo/assets/42337257/d18064f6-43c1-48ff-a770-d16d0b47c850
Android:
https://github.com/daimo-eth/daimo/assets/42337257/52895962-a64e-4ff4-a174-de3950c3d298
=> Make long press mandatory on confirm transaction

apps/daimo-mobile/src/view/screen/AccountScreen.tsx
Keyboard focus was broken when going to send screen from account screen. 
It opens correctly now
Closes #541
Android:
https://github.com/daimo-eth/daimo/assets/42337257/ceddb83c-a2b9-4050-97b4-8a23a4962b57
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/54fd33eb-078c-411e-b639-7649fc9f1fdc
=> Delay focus when go to send screen from account screen

apps/daimo-mobile/src/logic/passkey.ts
Tested on iOS and Android:
Android:
=> mobile: change passkey display title

apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/shared/Amount.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/shared/AnimatedSearchInput.tsx, apps/daimo-mobile/src/view/shared/Badge.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/ContactBubble.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/InputBig.tsx, apps/daimo-mobile/src/view/shared/IntroTextParagraph.tsx, apps/daimo-mobile/src/view/shared/text.tsx
Add maximum font size and don't allow font scaling in some places.
Maybe we should consider all <Text> being imported from text.tsx file instead of React Native but in this PR I added necessary prop to all instances without risk of breaking anything
Closes #449
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/043347b1-7848-434b-a162-4806a55c0c4a
Android:
https://github.com/daimo-eth/daimo/assets/42337257/215e0d3a-d11e-4b19-bb4c-cf2c89ace5b6
=> Add maximum font size to handle XL font on iOS

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx
Before it refreshed all list every time something called resync(), so every 5 seconds or even more often
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/f1634164-d480-44f6-9071-61058af42ad8
Android:
https://github.com/daimo-eth/daimo/assets/42337257/db11b53c-7741-4755-ae1f-c65b6359035c
=> perf: refresh history list only on change

apps/daimo-mobile/app.config.js, apps/daimo-mobile/package.json, apps/daimo-mobile/src/logic/deeplink.ts, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-web/public/.well-known/apple-app-site-association, apps/daimo-web/src/app/l/[[...slug]]/page.tsx, apps/daimo-web/src/components/AppOrWalletCTA.tsx, apps/daimo-web/src/components/CallToAction.tsx, package-lock.json, packages/daimo-api/src/api/getLinkStatus.ts, packages/daimo-common/src/daimoLink.ts
for #614 
- shorter link prefix `/l/` instead of `/link/`
- new `tag` type link that just redirects to a `request` in app and behaves as a request link in the API.
- android NDEF_DISCOVERED intent for smooth experience, handle tag launch events on startup as well.
TODO:
=> mobile: Add NFC tag deeplinks

apps/daimo-mobile/app.config.js
simplify `app.config.js`, consolidate regular deep links and NFC tap deep links
=> mobile: fix Play Console deeplinks warning

apps/daimo-mobile/src/logic/deeplink.ts, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx
https://streamable.com/xxf73e
Fixes #650 : if the app is launched by an initialURL during onboarding, it will double trigger action to it which looks bad after onboarding from payment links
=> mobile: do not double handle initalURL

apps/daimo-mobile/src/action/key.ts, apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/action/useExistingAccount.ts, apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/UseExistingPage.tsx
unify key load or creation to prevent race condition between createAccount and useExisting.
tested by running through onboarding > delete device a handful of times.
=> onboarding: fix key load or create race

packages/daimo-api/src/shovel/watcher.ts
Couple server fails in the last day with `Query read timeout` https://logs.betterstack.com/team/183561/tail?a=1706558645199434-104000491&rf=now-60m&q=syslog.host%3D%22daimo-api-prod%22
hotfix for now, in future we should add a retry loop
=> api: bump shovel limit

apps/daimo-mobile/src/view/shared/useSwipeUpDown.tsx
Closes #659
Handle bottom sheet so it works even after resizing on Mac OS (Still looks kinda strange while transition though but it usable)
Mac OS:
https://github.com/daimo-eth/daimo/assets/42337257/a8222bf8-b421-4595-a5e3-a6b043fd830d
After tests android and iOS seems to working same as before change
=> Use % instead of numbers to handle resize of Mac app

packages/daimo-api/src/shovel/watcher.ts
The latest version of shovel exposed a view that callers can use to see where Shovel is at in the chain.
https://github.com/indexsupply/code/pull/232
=> daimo-api: update shovel watcher to use latest shovel schema

apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/useSwipeUpDown.tsx
Remove react navigation from bottom sheet and use reanimated for smoother experience.
Closes #660
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/98f3606a-78b1-4036-9a32-037920a0c692
Android:
https://github.com/daimo-eth/daimo/assets/42337257/971b3993-3a25-4aed-9003-0caaeb9c3d0c
=> Remove react navigation from bottom sheet and use reanimated for smoother experience

apps/daimo-web/src/middleware.ts, apps/daimo-web/src/utils/platform.ts
=> web: redirect /l/download to App Store

apps/daimo-mobile/src/view/TabNav.tsx
Removing my interpolator seems to fix the backdrop issue on iOS
(My custom 🐢 breaks the interface but it is only pasted there for tests 🙏)
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/2ace716f-0739-47a3-bf1f-cb4fc8a0e639
Android:
https://github.com/daimo-eth/daimo/assets/42337257/20b192b1-d526-43c0-8843-f96d296d0697
=> Remove unnecessary interpolator

packages/daimo-common/src/daimoLink.ts, packages/daimo-common/test/daimoLink.test.ts
Keeping the `/link/` prefix around on the web-app for a while longer since it's free.
=> enable shorter /l/ links universally

apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx
- Uses the bounce from #688, but without changing the inner content
- (The video in #633 suggested changing the direction the inner content slides too--but added too much engineering complexity.)
https://github.com/daimo-eth/daimo/assets/169280/8ea046c1-9e3e-45d7-a136-ae406c8c836d
=> mobile: simplified bottom-sheet bounce

apps/daimo-mobile/src/view/TabNav.tsx
While laying in bed I realized I made a horrible, yet silly mistake: https://github.com/daimo-eth/daimo/pull/699 This PR actually changes modal animation a loooot, but I haven't realized at the time because I created my first draft by modifying the library code and then moving it into our codebase so after removal from our codebase it this PR it worked for me perfectly the same as before. But it shouldn't. 😳
So after reinstalling the stack library without my local changes it looks like this:
https://github.com/daimo-eth/daimo/assets/42337257/a016b427-7f36-4d1e-9681-3b20572d3484
https://github.com/daimo-eth/daimo/assets/42337257/c9d74135-d913-4e05-8ad0-53ca104f72b6
But after actually fixing it it looks like this:
https://github.com/daimo-eth/daimo/assets/42337257/fc67eeb0-c136-402c-9908-21c …
=> Re-add interpolator but working

apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/nav.ts
- Was annoying that these aren't clickable: https://streamable.com/oielrf
- stops disabling horizontal swipe, it was disabling the swipe even when an op was opened then closed.
=> mobile: history op screen improvements

apps/daimo-mobile/src/view/shared/SuggestedActionBox.tsx
Layout for button sometimes returned 0 on android so the whole action box was not possible to trigger. Now I calculate position of X button based on width of the action sheet because it's always working.
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/e0bd791c-cad2-4d10-81af-b3c755330623
Android:
https://github.com/daimo-eth/daimo/assets/42337257/f22b462d-4ab5-49cf-bf62-ad995be41f72
=> Fix action box responsiveness on Android

apps/daimo-mobile/app.config.js
Modify info.plist to block only 2 window size variants for Mac app to avoid ugly animations, and strange size variants
Mac:
https://github.com/daimo-eth/daimo/assets/42337257/0034ef1d-cbce-45ab-a119-edea552f7819
=> Modify info.plist to block only 2 window size variants for Mac app

apps/daimo-mobile/app.config.js
Master continous deploy is failing because 1.5.4 was released in #719 , public release versions cannot be re-used for canary internal builds: https://github.com/daimo-eth/daimo/actions/runs/7921106455/job/21625654302
=> update canary build number

apps/daimo-mobile/src/logic/daimoContacts.ts, apps/daimo-mobile/src/logic/systemContacts.ts, apps/daimo-mobile/src/view/screen/send/SearchResults.tsx
Tested on iOS simulator with:
- Two system contacts with same name, different email -> both show up and clickthrough correctly
- Two system contacts with same name, same email -> one shows up and click through correctly
- Two system contacts with different name, same email -> only one shows up and click through correctly
=> mobile: make contact search unique, fix list key bug

.github/workflows/ci.yml, apps/scratchpad/src/index.ts, packages/daimo-api/src/api/search.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/test/bundleCompression.test.ts, packages/daimo-api/test/dtest.ts
Tested on iOS simulator, looks like we weren't attaching the linkedAccounts to `EAccount`s from some API requests before -- this is nice because it gives us a negative diff also
=> api: fix Farcaster link not showing

apps/daimo-mobile/app.config.ts, apps/daimo-mobile/src/view/shared/HistoryList.tsx
**Fresh new look. Link Farcaster.**
=> release: 1.6.0

apps/daimo-web/src/app/SectionHero.tsx
This adds a white background within the phone frame in the hero section of the website to improve the appearance during page load (so the user doesn't see a phone frame without the center portion before the animation loads).
On a separate note: the gif is large, so we should consider optimizing it or swapping for a more efficient file format to improve the loading time and quality of the animation.
=> Improve hero phone appearance while animation loads

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/OfflineHeader.tsx
Closes #589
Make offline header turn on sync and show refresh control.
I created some small animation to smooth the transition but I don't know if it's worth it clean-code-wise so we can revert just one commit to remove it and make code a lot simpler but the refresh control will show a little more aggressively. Examples below:
With animation:
https://github.com/daimo-eth/daimo/assets/42337257/edaa7d57-006d-436a-8c6b-b3b0a0b76a73
Without animation:
https://github.com/daimo-eth/daimo/assets/42337257/fed06eec-f528-470d-9aa5-cd579db07cc6
=> Make offline header pressable on home screen

apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/shared/nav.ts
This PR fixes an issue where RN's `navigate` function replaces the account screen in-place instead of pushing a new one to the navigation stack. Swapping out `navigate` for `push` fixes the issue. It also fixes an issue where backward navigation on the `SendTab` screen incorrectly navigated to the `HomeTab` screen.
=> Push account screens correctly

apps/daimo-mobile/src/logic/daimoContacts.ts, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchResults.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/error.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-web/src/app/[...topLevelPage]/route.tsx, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-contract/src/index.ts
* show inviter when opening invite deeplink
* currently you just stay on the home screen, which feels like a bug
* include recent senders in search
Before this PR, this list would've been empty. (No recent recipients, 1 recent sender, now shown:)
If someone has paid you but you've never paid them before, you see the following:
=> mobile: include recent senders in search, improve /l/invite 

apps/daimo-web/package.json, package-lock.json
This PR downgrades `sharp` to version `0.32.6`, to prevent installation issues on Vercel
=> Downgrade sharp to get images to work

apps/daimo-mobile/src/view/screen/AccountScreen.tsx
Closes #827 
This PR prevents address information from getting repeated in the account screen's subtitle.
=> Prevent address repeat in subtitle

apps/daimo-mobile/src/view/shared/ContactBubble.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx
This PR fixes an issue that caused profile images to flicker unnecessarily. The issue was caused by a fresh instantiation of `TransactionList` in `SwipeUpDown` on every render. Moving the component out and lifting state into a context fixed the issue.
To properly test this PR, run it on a physical device. For some reason, the issue fixed is not reproducible on iOS simulators.
=> Fix issue with profile picture flicker

apps/daimo-mobile/src/view/screen/receive/ReceiveScreenV2.tsx
- make request screen transition non glitchy
- before: looked glitchy due keyboard popping up halfway and causing stack navigator to reset
- now: slower to show keyboard, but non glitchy.
=> Release fixes

apps/daimo-mobile/app.config.ts, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/logic/log.ts, apps/daimo-mobile/src/logic/passkey.ts, apps/daimo-mobile/src/view/screen/keyRotation/AddKeySlotButton.tsx, packages/daimo-expo-passkeys/ios/PasskeyManager.swift
Tested it fixes the issue consistently, deleted app and reinstalled and immediately clicked restore from backup ~10 times.
Additionally, remove .xyz domains just in case they can cause issues.
Example log:
=> Passkeys: Retry backoff creation on domain association errors

apps/daimo-mobile/app.config.ts
**Profile pics, invite tab, and more.**
<details>
<summary><strong>Debug log shows following error on device screen.</strong></summary>
```
2024-03-13T10:33:56.386Z log [APP] rendering
2024-03-13T10:33:56.389Z log [ERROR] rendering Cannot read property 'slot' of undefined TypeError: Cannot read property 'slot' of undefined
at DeviceScreen (/Users/expo/Library/Developer/Xcode/DerivedData/Daimo-fqyuburyhitsbcesjtzisutllqsr/Build/Intermediates.noindex/ArchiveIntermediates/Daimo/BuildProductsPath/Release-iphoneos/main.jsbundle:355135:23)
at renderWithHooks (/Users/expo/Library/Developer/Xcode/DerivedData/Daimo-fqyuburyhitsbcesjtzisutllqsr/Build/Intermediates.noindex/ArchiveIntermediates/Daimo/B …
```
=> release: 1.7.0

apps/daimo-bot/api/botResponses.ts, apps/daimo-bot/api/daimobotProcessor.ts, apps/daimo-bot/api/test/index.test.ts, apps/daimo-bot/api/test/jest.setup.ts, apps/daimo-bot/api/trpcClient.ts, packages/daimo-api/src/db/db.ts
- Bug fix: In a [commit](https://github.com/daimo-eth/daimo/pull/849/commits/401371386db8338a90093e8c76e5c8841e2c8c96#diff-b04d6b44b7d2a7d3526c2f8624323be7b4a017eb3947b9372acbc37e5e2fea11) on previous PR, removed `/chain/<chainId>` from URI. This PR adds it back in.
- Includes payment request URL in cast responses
- Cast response amount always displays 2 dec places
- Ignores when daimobot tags itself
=> Daimobot tweaks after initial testing

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchResults.tsx, apps/daimo-mobile/src/view/shared/AnimatedSearchInput.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx
Closes #829
The reason why thing in the video happens is that sometimes it's possible to accidentally close the keyboard and it results in closing whole search list.
This PR makes it so it only do so if the input is empty or the back arrow is pressed.
On refocus it clears the input right now but it can be easily changed.
Also the keybaord padding can be animated using useAnimatedKeyboard but wanted to let this PR be simpler and change it in future PR if necessary
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/107ca88b-2d11-4a04-b04b-0e25f3da7d94
=> Don't close search when accidentally dismiss keyboard

apps/daimo-web/src/app/profile/[...addr]/route.tsx
This PR fixes an issue where FC profile pictures did not appear on account screens for a while after they were already visible on other screens (particularly the Invite screen). They only became visible on subsequent screen loads.
Main:
- Invite a user and have them create an account
- Open their account screen
- Go back to the invite screen
- Have them link their FC account
- Navigate to the account screen again (the profile picture does not appear)
Hack (useful in both dev/prod testing:)
- Unlink an FC account from an invited Daimo account
- Open the invited account's account screen
- Go back to the invite screen
- Re-link the FC account
- Navigate to the account screen again (the profile picture does not appear)
This PR sets the `gcTime` property of the `useFetchLinkStatus` query to …
=> Fix delay in updating profile pictures after invites

packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/server/cron.ts, packages/daimo-api/src/utils/retryBackoff.ts
We had slight downtime for ~10min today because Alchemy (our fallback RPC) was 503ing, acknowledged by them on [status](https://status.alchemy.com) -- this fixes future reliability issues with viem's fallback transport. More about fallback transport and the ranking criteria [here](https://viem.sh/docs/clients/transports/fallback).
Tested locally with two RPCs.
Additionally, it turns out `viem` internally does have a retry loop for RPCs failing spuriously, so altogether this closes #922
=> api: misc. reliability improvements

apps/daimo-mobile/src/logic/accountManager.ts, apps/daimo-mobile/src/view/sheet/HelpBottomSheet.tsx, apps/scratchpad/package.json, apps/scratchpad/src/index.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/test/dtest.ts
The current ShovelWatcher loads 2 blocks at a time!
```
[SHOVEL] loaded 12456222 to 12456223 in 14ms
[...]
[SHOVEL] loaded 12456224 to 12456225 in 23ms
```
This PR fixes that, and also speeds up API server startup significantly. (Now that we are filtering transfers and ops + using retryBackoff, we can go back to using a 100k-block batch size.)
Users should see transfers confirm 1s faster on average and 2s faster worst-case due to this fix.
fixes #860
=> small fixes

packages/daimo-api/src/network/viemClient.ts
Tested on local API saves ~50ms.
Likely fixes #935 as well -- though the exact cause of that is still unclear to me.
=> viem client: save eth_chainId roundtrip

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/logic/onboarding.ts, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/style.ts, apps/daimo-mobile/src/view/sheet/DebugBottomSheet.tsx, apps/daimo-mobile/src/view/sheet/FarcasterBottomSheet.tsx, apps/daimo-mobile/src/view/sheet/GlobalBottomSheet.tsx, apps/daimo-mobile/src/view/sheet/OnboardingChecklistBottomSheet.tsx
This puts the button always in the same spot, and gracefully handles smaller phones.
=> mobile: onboarding, bottom sheet fixes

apps/daimo-mobile/app.config.ts
**Memos, in-app requests, onboarding checklist.**
=> release: 1.8.0

packages/daimo-api/src/api/getMemo.ts, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/server.ts
Add a getMemo() api endpoint to retrieve the Daimo payment memo for a given transaction (as defined by its txHash and logIndex). 
Inputs: transaction hash, log index. 
Output: transaction hash, log index, user op, memo.
=> feat: Add get memo api endpoint

packages/daimo-api/src/server/router.ts
=> api: bring back deprected verifyInviteCode endpoint

.github/PULL_REQUEST_TEMPLATE/release.md, apps/daimo-mobile/.maestro/shared/createAccount.yaml, apps/daimo-mobile/app.config.ts
**Receive any coin, swap to USDC.**
Do this with the Mac app, check for visual regressions.
=> release: 1.8.6

apps/daimo-mobile/src/view/screen/QRScreen.tsx, apps/daimo-mobile/src/view/sheet/DepositAddressBottomSheet.tsx
- show ending letters of address on deposit screen: that's what users use to authenticate the address on copying it elsewhere, and its annoying right now to not be able to see those
- allow long press to copy raw address on qr screen -- noticed Daniel from Bountycaster do this and he explained he wanted this interaction since there's no easy way to get address from that screen.
=> mobile: small UX improvements to deposit address flow

packages/daimo-api/src/network/uniswapClient.ts
Observed bug: foreign coin swaps not working at all, not for DOGINME and not for USDbC, unable to reproduce on running prod API server with simulator on my local.
on investigating logs:
```
[UNISWAP] fetching swap for 0x27785Ad361898B526F37d87C4fAcFD757Ff0622F 0xd9aAEc86B65D86f6A7B5B1b0c42FFA531710b6CA
```
happens but no logs from `[UNISWAP]` even though we are supposed to always log returned information from the SDK -- it's also unclear if there was an error why `retryBackoff` did not trigger.
Googling finds other reports of similar issues, apparently from Ethers Websocket being broken.
Fix: use HTTP RPC for the Uniswap SDK instead, added env variables to prod and testnet APIs.
=> uniswap client: workaround ethersJS bug

packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/contract/homeCoinIndexer.ts
Fixes:
Fixes balance out of sync of displayed transfers, unclear why that could happen.
=> api: use balance from shovel instead of client

packages/daimo-api/src/api/getAccountHistory.ts
=> hotfix: api: no null invitees

apps/daimo-mobile/src/sync/sync.ts, packages/daimo-api/src/api/getAccountHistory.ts
tested in iOS sim testnet by restarting app a couple times, various pending states etc.
=> api, mobile: protect from bad finBlock sync

apps/daimo-mobile/app.config.ts, apps/daimo-mobile/src/view/screen/onboarding/ExistingUseBackupScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/MissingKeyScreen.tsx, packages/daimo-api/Dockerfile
=> release: 1.8.7

packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-common/src/op.ts
The `pushNotifier.test.ts` suite seems pretty redundant tbh -- I think we could write a much better test suite that puts a mock shovel database and runs off of that in future.
=> api: fix double notif on payment link claim

.github/workflows/cd.yml
Let me know if you'd like any changes. Builds and deploys api on each push to `master` and `prod`. Successful run can be seen [here](https://github.com/daimo-eth/daimo/actions/runs/9225477659/job/25383053568).
=> deploy api image via github actions

.github/workflows/cd.yml
Updates cd so that it first checks whether an image exists with the git sha so that the build/push can be skipped. If it needs to deploy, it will build and deploy using docker, utilizing caching.
=> improve api deploy

apps/daimo-mobile/src/logic/accountManager.ts, apps/daimo-mobile/src/view/screen/onboarding/ExistingScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingIntroScreen.tsx
bad onboarding bug on android, no key is generated in the use existing flow at the moment:
> 2024-05-27T21:50:18.630Z ERR ExpoEnclaveSign: Encountered an exception while calling native method: Exception occurred while executing exported method sign on module ExpoEnclave: null
=> android: fix null error

packages/daimo-api/src/server/server.ts
Looks like some weird bugs due Quicknode breaking and not working well with the `updateLastProcessedCheckStale` which doesn't account for it -- will just disable for now and bring it back in #1035 properly, additionally fixing #1082.
Tested API still works fine.
=> api: disable ethIndexer for now, bugs

packages/daimo-api/src/server/coinList.ts
Handles invalid addresses such as:
=> ignore invalid CoinGecko addresses

packages/daimo-api/src/api/getExchangeRates.ts, packages/daimo-common/src/currencies.ts
Unlike Chainlink, OpenExchangeRates supports currencies like ARS (Argentine Pesos) and NGN (Naira).
=> api: use OpenExchangeRates, add currencies

apps/daimo-web/src/app/l/[[...slug]]/page.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/app/preview/route.tsx, apps/daimo-web/src/components/image-gen/LinkPreview.tsx, apps/daimo-web/src/components/image-gen/UserBubble.tsx, apps/daimo-web/src/utils/getProfilePicture.ts
Adds profile picture to link preview if a profile picture exists for the given Daimo account. 
**Link Preview**
Before:
After:
**Web page**
Before:
After:
=> feat: add profile picture to link preview

packages/daimo-api/src/contract/ethIndexer.ts, packages/daimo-api/src/server/server.ts
Eth Transfers are not showing up in-app due to the ethIndexer being disabled because of RPC failures (see https://github.com/daimo-eth/daimo/pull/1089).
This PR simplifies ethIndexer to simply fetch the latest cached balance for the given address. If there is a positive balance difference between the cached balanced and the new balance, then adds to newTransfers.
=> [fix] RPC downtime error handling for ETH transfers

packages/daimo-api/src/server/cron.ts, packages/daimo-api/src/server/server.ts
Adds ETH transfer notifications to clippy to track when a user receives ETH. Currently not being reported by Clippy.
=> clippy: Add ETH transfer notifications to clippy

.github/workflows/cd.yml, apps/daimo-bot/Dockerfile, apps/daimo-clippy/Dockerfile
Couldn't find a nice way to share the common steps between jobs so just repeated them. Also adds `ts-node` as a devDependency to clippy matching the bot setup (`tsx` was failing to run on the docker image).
=> add bot & clippy to cd

apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/utils/linkMetaTags.ts
this is the only way I know to cache bust telegram link preview images, also did a "purge cache" in vercel project
=> web: cache bust previews without profile pics

packages/daimo-api/src/contract/ethIndexer.ts, packages/daimo-api/src/server/cron.ts
Only change cache when there is a balance difference instead of updating cache for all accounts every index.
=> api: ethIndexer caching changes

packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/telemetry.ts
Addresses https://github.com/daimo-eth/daimo/issues/1133.
API not ready should not be sent to Sentry as an Error.
=> sentry: filter out API "not ready" logging errors

packages/daimo-contract/src/shovel/config.json
Simple but effective change.
```
eth_sources[].ws_url
An optional URL that points to a Websocket JSON RPC API. If this URL is set Shovel will use the websocket to get the latest block instead of calling eth_getBlockByNumber. If the websocket fails for any reason Shovel will fallback on the HTTP based API
```
More: https://www.indexsupply.com/shovel/docs/#config-eth-sources-ws-url
This requires adding CHAIN_RPC_WS_URL env var to Shovel service.
closes https://github.com/daimo-eth/daimo/issues/1109
=> Use Websocket in Shovel for realtime block ingestion

packages/daimo-api/src/api/getSwapRoute.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/server/tokenRegistry.ts
* resolve pending swaps for old ETH inbounds
* remove excessive coupling in `foreignCoinIndexer` between CoinGecko responses & our own ForeignToken type. the former has `address: "0x..."`, the latter needs to have `token: "0x..."` & is used in Daimo API.
Both eth and erc20 receive should work now.
=> api: resolve pending swaps for old ETH inbounds

packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/src/utils/cache.ts
- Cache finalized block fetching globally. Before `getBlock` RPC call was made for every `getAccountHistory` request. Now the value is refreshed at most once every 1s. More: #1180
- Fix a bug where `AccountHistoryResult` could be one block behind. Now we get latest indexed block from Shovel database instead from internal `Watcher` indexer in `getAccountHistory`. This bug occurred when event loop called a new block notification callback in `Watcher.watch` before one in `onAccountUpdate` TRPC subscription.
=> Streamline latest block access & finalized block caching

apps/daimo-web/src/app/l/[[...slug]]/page.tsx
=> web: fix pfp ratio on invite page

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/common/nav.ts, apps/daimo-mobile/src/logic/accountManager.ts, apps/daimo-mobile/src/storage/account.ts, apps/daimo-mobile/src/storage/storedTypeMigrations.ts, apps/daimo-mobile/src/storage/storedTypes.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/history/HistoryList.tsx, apps/daimo-mobile/src/view/screen/history/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/sheet/SwapBottomSheet.tsx, apps/scratchpad/src/index.ts, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/contract/SwapClogMatcher.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/contract/homeCoinIndexer.ts, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/offchain/inviteCodeTracker.ts, packages/daimo-api/src/server/cron.ts, packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/src/server/tokenRegistry.ts, packages/daimo-api/test/dtest.ts, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/foreignToken.ts, packages/daimo-common/src/op.ts
Previously, we had `DisplayOpEvent`. 
This PR refactors naming from `DisplayOpEvent` to `TransferClog`. A `TransferClog` can be one of three things: 
- a `SimpleTransferClog` # alice to bob, same chain, same coin
- a `SimplePaymentLinkClog` # alice to payment link (and once bob claims, alice > payment link > bob), same chain, same coin
- a `SwapClog` # alice to bob, same chain, different coins (inbox, any-coin send)
This allows a transfer to accurately show the correct "from" and "to" endpoints in the case where a transaction occurs over the span of multiple transfer logs (e.g. needs to route over swap pools to get to end destination). 
**Before** (shows direct log transfer): 
**After** (shows clog endpoints; pending and finalized):
=> api, mobile: refactor opEvent to Clog

apps/daimo-mobile/src/logic/notify.ts, apps/daimo-mobile/src/logic/trpc.tsx, apps/daimo-mobile/src/sync/networkState.ts, apps/daimo-mobile/src/sync/sync.ts, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/shovel/watcher.ts
websocket implementation was unreliable. fixes spurious offline indicator.
we are still using websockets to talk to ethererum RPC (both API & shovel), & postgres NOTIFY for api to get rapid updates from shovel.
This PR deletes the materialized views that were causing us grief. As a stopgap till a more permanent indexer fix, this should restore inbox functionality, including receiving ETH.
=> mobile: revert to normal polling, fix foreignCoinIndexer

apps/daimo-mobile/src/view/shared/SearchResults.tsx
Fixes https://github.com/daimo-eth/daimo/issues/1070
Bottom recent recipient doesn't get cut off anymore
=> Add padding to bottom of search results

packages/daimo-api/src/network/viemClient.ts
Fixes nonce issue in https://github.com/daimo-eth/daimo/issues/1246
5 transactions with nonces 1, 2, 3, 4, 5 get sent. Tx 1 gets rejected but tx 2-5 are queued by the sequencer.
Without the fix, the client would send new txs with nonces 6, 7, 8, ... These new txs will fail with a "receipt error" because a tx with nonce 1 hasn't been sent yet.
With the fix, the client will time out waiting for the receipts of txs 1-5, then it would send the next tx with nonce 1. Txs 2-5 will get processed. `updateNonce` will query the next nonce from the RPC and set the nonce of the next tx to 6.
=> API: fix nonce issue

packages/daimo-api/src/db/db.ts
Fixes API error:
```
error: duplicate key value violates unique constraint "push_notification_address_push_key_key"
```
...`tryInsertPushNotifications` is meant to dedupe outbound push notifications > now does that correctly
=> api: fix tryInsertPushNotifications

packages/daimo-api/src/api/healthCheck.ts, packages/daimo-api/src/contract/indexer.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/src/server/shovelSquared.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-common/src/currencies.ts
New indexing flow:
- Blocks available in `latest` = data available in `eth_transfers`, `erc20_transfers`, and `erc4337_user_op`
- ShovelSquared tracks this, updates `blocks`, `daimo_transfers`, `daimo_ops` and finally `daimo_index`
- Watcher tracks blocks available in `daimo_index`, updates in-memory index
=> api: hotfix watcher, ShovelSquared

.github/PULL_REQUEST_TEMPLATE/release.md, apps/daimo-mobile/app.config.ts
**Any-chain send.**
N/A, not updating prod API until later.
=> release: 1.9.3

apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/test/nav.test.ts, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/components/ConnectWalletFlow.tsx, apps/daimo-web/src/utils/linkStatus.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/daimoLinkStatus.ts, packages/daimo-common/src/foreignToken.ts, packages/daimo-common/test/daimoLink.test.ts
https://github.com/daimo-eth/daimo/issues/1263
- fix issues in daimo-web where `DaimoRequestLink` is used
- handle case where the recipient is a Daimo account but the `toChain` is not base or the `toCoin` is not USDC
=> Support any-chain request links

apps/daimo-mobile/src/logic/daimoContacts.ts, apps/daimo-mobile/src/view/screen/DepositScreen.tsx, packages/contract/test/AccountFactory.t.sol, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/api/search.ts, packages/daimo-api/src/contract/indexer.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/src/utils/cache.ts, packages/daimo-common/src/op.ts, packages/daimo-expo-enclave/README.md, packages/daimo-expo-enclave/ios/SecureEnclaveKeyManager.swift, packages/daimo-expo-passkeys/ios/AuthResponder.swift
Includes writing 'thru' as 'through'.
All changes are non-functional in comments or READMEs and should have no effect on the app, just helps maintain the code base.
This is easiest to review with command `git show --word-diff` if pulling locally.
=> Fix misc typos

apps/daimo-mobile/src/common/nav.ts, apps/daimo-mobile/src/logic/linkStatus.ts, packages/daimo-common/src/invite.ts
When clicking a tag deeplink that redirects to an invite link, it doesn't autofill the invite code.
Messed up and didn't notice this issue in this PR :(
https://github.com/daimo-eth/daimo/pull/1276
Created an invite code called `test` and a tag called `test` which redirects to `https://daimo.com/l/invite/test`.
Created an invalid invite code called `test` and a tag called `test1`.
Created a tag called `request` which redirects to `https://daimo.com/l/request?to=vitalik.eth&c=84532&t=usdc`
| link       | result       |
|----------------|----------------|
| daimo://t/test | redirects to "choose username"  |
| daimo://invite/test  | redirects to "choose username"  |
| daimo://t/test1  | redirects to "enter invite code" |
| daimo://invite/test1  | redirects to "enter invite code" |
| …
=> mobile: handle tag deeplinks during onboarding

apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/screen/history/HistoryList.tsx
Now in HistoryList inside the daimo app, the Months can be in multiple languages.
Made a small change inside `view/screen/history/HistoryList.tsx`, it retrives the locale, sets it to 'default' if null, then we use it inside `toLocaleString(language)` in line 129.
Encountered small problem with Spanish, it returned the first letter of the month in lowercase, added code to ensure the first letter of the month is in uppercase.
- first draft
- fix Months in HistoryList
=> Fixed Months in timelime in app

packages/daimo-api/src/db/indexWatcher.ts
Fixes https://github.com/daimo-eth/daimo/issues/1319
Issue where name says "available" on testnet even though it's not. This is because our testnet indexer loads from a later block than when NameReg started. the earliest name registered on testnet is on block `5893972`. Both testnet and mainnet start from `5700000` for simplicity. 
Now says `name is unavailable`:
=> indexer: start from beginning on testnet

apps/daimo-mobile/app.config.ts, apps/daimo-mobile/src/common/nav.ts, apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/view/screen/LandlineBankTransfer.tsx, apps/daimo-mobile/src/view/screen/send/CoinDisplay.tsx, apps/daimo-mobile/src/view/screen/send/MemoDisplay.tsx, apps/daimo-mobile/src/view/screen/send/RouteDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/sheet/BitrefillBottomSheet.tsx, apps/daimo-mobile/test/nav.test.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/eAccount.ts, packages/daimo-common/test/daimoLink.test.ts
=> release: 1.9.10

apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx
Fixes the `isSwap` check for asserting the transfer is not a bridge+swap. 
Tokens have different addresses on different chains (e.g. Base USDC token addr != Arb USDC token addr), so must instead check that the `toCoin` address is not the same as the `bridgeCoin` for the `toChain` to check whether it's a swap
=> mobile: fix cross-chain check

apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/screen/LandlineTransferScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx
I missed a commit last night in #1340
=> mobile: fix cross-chain send preview

apps/daimo-mobile/app.config.ts
**Better deposits and cross-chain sends.**
* Lets us ship Landline
**Request memos don't appear correctly on web. Fixed here: https://github.com/daimo-eth/daimo/pull/1344**
=> release: 1.9.11

packages/daimo-api/src/api/healthCheck.ts, packages/daimo-api/src/codegen/dbIndex.ts, packages/daimo-api/src/db/indexWatcher.ts
- add block latencies to indexer debug health check
=> api: indexer debug health check

packages/daimo-api/src/api/getAccountHistory.ts
Fixes issue https://github.com/daimo-eth/daimo-internal/issues/146
Remove landline from the deposit page but keep landline transfers in the transfer history
=> daimo api: disable landline

apps/daimo-mobile/src/action/dispatch.ts, apps/daimo-mobile/src/logic/paymentURI.ts, apps/daimo-mobile/src/view/screen/deposit/BitrefillWebview.tsx, apps/daimo-mobile/src/view/sheet/BitrefillBottomSheet.tsx, apps/daimo-mobile/src/view/sheet/GlobalBottomSheet.tsx, apps/daimo-mobile/test/paymentURI.test.ts
=> mobile: use bitrefill new parse

packages/daimo-common/package.json, packages/daimo-common/src/daimoPay.ts, packages/daimo-contract/package.json
- add `paymentChains` parameter to filter EVM chains
- add solana and external chains to `paymentOptions`
=> pay common & contract v1.3.4: improve payment option filtering
