daimo-eth/daimo

.gitignore, .vscode/settings.json, package-lock.json, package.json, packages/daimo-api/src/index.ts, packages/daimo-api/src/nameRegistry.ts, packages/daimo-mobile/package-lock.json, packages/daimo-mobile/package.json, packages/daimo-mobile/src/App.tsx, packages/daimo-mobile/src/logic/account.ts, packages/daimo-mobile/src/logic/chain.ts, packages/daimo-mobile/src/view/screen/DepositScreen.tsx, packages/daimo-mobile/src/view/screen/HomeScreen.tsx, packages/daimo-mobile/src/view/screen/OnboardingScreen.tsx, packages/daimo-mobile/src/view/screen/ReceiveScreen.tsx, packages/daimo-mobile/src/view/screen/RequestScreen.tsx, packages/daimo-mobile/src/view/screen/SendScreen.tsx, packages/daimo-mobile/src/view/screen/UserScreen.tsx, packages/daimo-mobile/src/view/shared/Header.tsx, packages/daimo-mobile/test/account.test.ts, packages/daimo-mobile/tsconfig.json, packages/expo-enclave/package.json
I set #14 to automerge, and it merged even though tests failed for some reason.
I've made tests non-bypassable to fix this.
* Here's a follow-up PR that fixes the type errors. 
* It also tells VS Code to use a specific version of typescript for reproducibility.
* Finally, it enables `strict` mode for `daimo-mobile` and fixes a number of revealed type issues.
=> Fix Typescript config

.github/workflows/ci.yml, packages/daimo-contract/package.json, turbo.json
=> npm build without foundry

apps/daimo-mobile/app.json, apps/daimo-mobile/package.json, apps/daimo-mobile/src/logic/env.ts, apps/daimo-mobile/src/view/screen/ChainScreen.tsx, apps/daimo-mobile/src/view/screen/UserScreen.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/style.ts, package-lock.json, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/BiometricsKeyManager.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/ExpoEnclaveModule.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/FallbackKeyManager.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/KeyManager.kt, packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift, packages/daimo-expo-enclave/ios/FallbackKeyManager.swift, packages/daimo-expo-enclave/ios/KeyManager.swift, packages/daimo-expo-enclave/ios/SecureEnclaveKeyManager.swift, packages/daimo-expo-enclave/src/index.ts, packages/daimo-userop/src/daimoOpBuilder.ts, packages/daimo-userop/src/index.ts
=> expo-enclave: deleteKeyPair

apps/daimo-mobile/src/view/HomeStack.tsx, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/UserScreen.tsx, apps/daimo-mobile/src/view/shared/Header.tsx, apps/daimo-mobile/src/view/shared/nav.ts
=> Show key security level

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/logic/chain.ts, apps/daimo-mobile/src/logic/notify.ts, apps/daimo-mobile/src/view/screen/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/ReceiveScreen.tsx, apps/scratchpad/package.json, apps/scratchpad/src/index.ts, apps/scratchpad/tsconfig.json, package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/chain.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/index.ts, packages/daimo-api/src/pushNotifier.ts, packages/daimo-userop/src/index.ts
=> Notifications

apps/daimo-mobile/src/view/HomeStack.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/send/WithdrawScreen.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/style.ts
=> Withdraw screen

apps/daimo-mobile/src/action/actStatus.ts, apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/logic/enclave.ts, apps/daimo-mobile/src/logic/log.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/scratchpad/src/index.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/router.ts, packages/daimo-userop/src/index.ts
Cache DaimoAccount init
~1500ms to signing
```
LOG  [ACTION] 0ms: loading Loading account...
LOG  [ACTION] 24ms: loading Signing...
```
=> Faster send

apps/scratchpad/README.md, apps/scratchpad/package.json, apps/scratchpad/src/checkAccount.ts, apps/scratchpad/src/createAccount.ts, apps/scratchpad/src/index.ts, package-lock.json
Adds the following command to generate a BCC from a CSV containing `Name` and `Email` columns.
```
cd apps/scratchpad
npm start mailing-list <path to csv>
```
=> Scratchpad mailing-list

apps/daimo-mobile/app.json, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/logic/coin.ts, apps/daimo-mobile/src/logic/recipient.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/model/accountHistory.ts, apps/daimo-mobile/src/model/op.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/HomeStack.tsx, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/ChainScreen.tsx, apps/daimo-mobile/src/view/screen/History.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ClaimNoteScreen.tsx, apps/daimo-mobile/src/view/shared/AddrText.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/Header.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/opStatus.tsx, apps/daimo-mobile/src/view/shared/style.ts, apps/daimo-mobile/src/view/shared/text.tsx, apps/daimo-mobile/src/view/shared/time.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/model.ts, packages/daimo-api/src/pushNotifier.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts
=> Transfer history

apps/daimo-mobile/app.json, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/model/accountHistory.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/History.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/AddrText.tsx
=> Show pending transactions

apps/daimo-mobile/src/logic/chain.ts, apps/daimo-mobile/src/logic/enclave.ts, apps/daimo-mobile/src/logic/log.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx
Also fix history sort
Fixes #62
=> Delete unused signing keys

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/model/accountHistory.ts, apps/daimo-mobile/src/model/op.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/HomeStack.tsx, apps/daimo-mobile/src/view/screen/History.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/AddrText.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/style.ts
- Show faucet payment in history
- Fix pending sends, show recipient name
- Swipe gesture to show full history
=> Better history display

apps/daimo-mobile/app.json, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/ChainScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/RequestScreen.tsx, apps/daimo-mobile/src/view/screen/send/CancelHeader.tsx, apps/daimo-mobile/src/view/screen/send/CreateNoteTab.tsx, apps/daimo-mobile/src/view/screen/send/ScanTab.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/style.ts
=> Fix onboarding spacing, "... is requesting" message

packages/daimo-api/src/chain.ts
This makes the API resilient to occasional JSON RPC errors.
For context:
- **The main Base Goerli RPC is unreliable.** Earlier this week, we started seeing the following error frequently in getLogs: https://github.com/ethereum-optimism/optimism/issues/2618
- **QuickNode at least gives good error messages, but sometimes rate-limits us.** getLogs is restricted to 10k blocks at a time, requiring pagination to populate the index. Paging too fast occasionally throws `429 Too Many Requests`.
=> Add retry with backoff

apps/daimo-mobile/app.json, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/History.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ClaimNoteScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/RequestScreen.tsx, apps/daimo-mobile/src/view/screen/send/CancelHeader.tsx, apps/daimo-mobile/src/view/screen/send/CreateNoteTab.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/screen/send/WithdrawScreen.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/Header.tsx, apps/daimo-mobile/src/view/shared/InfoLink.tsx, apps/daimo-mobile/src/view/shared/Spacer.tsx, apps/daimo-mobile/src/view/shared/style.ts, apps/daimo-mobile/src/view/shared/text.tsx
=> Account screen, history polish

apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/shared/time.ts
=> Make history op screen much more minimal

apps/daimo-web/src/app/globals.css, apps/daimo-web/src/app/layout.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/app/page.tsx, apps/daimo-web/tailwind.config.js, packages/daimo-api/src/chain.ts
=> Website copy

apps/daimo-web/src/app/link/[[...slug]]/page.tsx
=> Web: font size

apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/RequestScreen.tsx, apps/daimo-mobile/src/view/screen/send/CreateNoteTab.tsx, apps/daimo-mobile/src/view/shared/style.ts, apps/scratchpad/assets/push-receive.apns, apps/scratchpad/src/index.ts
=> Send Note polish

apps/daimo-explorer/package.json, apps/daimo-explorer/prisma/schema.prisma, apps/daimo-explorer/src/app/addr/[[...slug]]/page.tsx, apps/daimo-explorer/src/app/op/[[...slug]]/page.tsx, apps/daimo-explorer/src/lib/utils.ts, package-lock.json
=> Extremely simple op and addr pages starting point

apps/scratchpad/src/index.ts, packages/daimo-api/src/chain.ts
This may help solve event log receiving reliability issues. See #130 
Added error logging.
=> API: connect to node via websocket

apps/daimo-mobile/index.js, apps/daimo-mobile/src/debugLog.ts, apps/daimo-mobile/src/logic/notify.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/test/account.test.ts
```
{"storageVersion":3,"enclaveKeyName":"daimo-7","name":"jimbo","address":"0x89eF445CC71A25107aB76e6433207848897a8fED","lastBalance":"0","lastBlock":8012505,"lastBlockTimestamp":1691218626,"lastFinalizedBlock":8011918,"recentTransfers":[],"namedAccounts":[],"pushToken":"ExponentPushToken[dmOmTsDc8F24h0viz6e0cA]"}
2023-08-05T06:57:06.224Z Running "main" with {"rootTag":91,"initialProps":{}}
2023-08-05T06:57:06.278Z [APP] rendering
2023-08-05T06:57:06.309Z [HOME] rendering with account jimbo
2023-08-05T06:57:06.364Z [SYNC] APP LOAD, starting sync
2023-08-05T06:57:06.364Z [SYNC] RESYNC jimbo, interval 30s
2023-08-05T06:57:06.382Z [LOG] {"type":"ExpoEnclave.fetchPublicKey","startMs":1691218626358,"elapsedMs":24}
2023-08-05T06:57:06.382Z [ENCLAVE] loaded daimo-7 = …
```
=> Send debug log

apps/daimo-mobile/src/sync/loadRecipients.ts, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/shared/addr.tsx, apps/daimo-mobile/src/view/shared/time.ts
=> Recent recipients

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/sync/recipients.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ClaimNoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/addr.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/scratchpad/src/index.ts, packages/daimo-api/src/chain.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/contract/noteIndexer.ts, packages/daimo-api/src/pushNotifier.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts, packages/daimo-common/src/daimoLinkStatus.ts, packages/daimo-common/src/model.ts
=> Send to ENS

apps/daimo-mobile/app.json, apps/daimo-mobile/src/logic/notify.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/scratchpad/assets/push-receive.apns, packages/daimo-api/src/contract/nameRegistry.ts
=> sync: save ENS namedAccounts

apps/daimo-mobile/src/logic/enclave.ts, apps/daimo-mobile/src/view/screen/AccountScreen.tsx
=> fix: AccountScreen, show Clear Wallet

apps/daimo-mobile/src/view/screen/AccountScreen.tsx
```
{
"Platform": "ios 16.4",
"Version": "0.1.0 #24",
"Commit": "unknown local",
"Notifications": "enabled",
"Key Security": "software key, PIN"
}
{"storageVersion":3,"enclaveKeyName":"daimo-7","name":"dc6","address":"0x757c8449893a81b614D6e83C0c819AD59136851A","lastBalance":"50000000","lastBlock":8185225,[...]
2023-08-09T06:49:22.202Z log [SYNC] got history 
[...]
```
=> add environment to Send Debug Log

apps/daimo-mobile/app.json, apps/daimo-mobile/package.json, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, package-lock.json
=> enable faceID

apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/debugLog.ts, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/shared/text.tsx
=> fix: OnboardingScreen checkbox > lock icon

.vscode/settings.json, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/logic/note.ts, apps/daimo-mobile/src/view/HomeStack.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/CreateNoteTab.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, package-lock.json, packages/daimo-common/src/coin.ts, packages/daimo-userop/src/index.ts
=> show Payment Link status

apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/logic/enclave.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/receive/SendRequestScreen.tsx, apps/daimo-mobile/src/view/screen/send/CreateNoteTab.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/test/account.test.ts, apps/daimo-testbed/App.tsx, apps/daimo-web/README.md, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/scratchpad/src/createAccount.ts, packages/daimo-api/package.json, packages/daimo-api/src/contract/coinIndexer.ts, packages/daimo-api/src/contract/faucet.ts, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/daimoLinkStatus.ts, packages/daimo-common/src/model.ts, packages/daimo-common/src/op.ts, packages/daimo-common/test/daimoLink.test.ts, packages/daimo-userop/package.json, packages/daimo-userop/src/index.ts, packages/daimo-userop/src/nonce.ts, packages/daimo-userop/test/nonce.test.ts
=> Request: Track fulfillment status

.github/PULL_REQUEST_TEMPLATE/release.md, README.md
=> doc: add release checklist

apps/daimo-mobile/src/view/shared/InputBig.tsx, apps/daimo-mobile/src/view/shared/nav.ts, package-lock.json
=> fix: deep links, SearchTab password input

apps/daimo-mobile/src/action/actStatus.ts, apps/daimo-mobile/src/view/HomeStack.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-common/src/index.ts, packages/daimo-common/src/name.ts, packages/daimo-common/test/name.test.ts
Closes #186 
Based on #201 don't merge till that's merged.
=> Onboarding: Re-order pages to hide loading behind notifications prompt

apps/daimo-mobile/src/view/screen/send/SendScreen.tsx
Closes #168 
The other two were fixed by the other PRs incidentally (add/remove made account page scrollable, #165 made recent transactions attached to the bottom)
=> Use Keyboard Avoiding View on Send screen

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/scratchpad/src/index.ts, package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/chain.ts, packages/daimo-api/src/contract/noteIndexer.ts, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts
Plus local file cache for fast restart
before: several minutes to resync `getLogs` from scratch
after: 12 seconds
=> Polling-based log sync

apps/daimo-mobile/app.json, packages/daimo-expo-enclave/package.json
**Add or remove device, faster onboarding, better home screen, better sync.**
=> release 0.1.0 build 37

apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/shared/nav.ts, packages/daimo-api/src/router.ts
fixes #198 
fixes #199 
fixes #209
=> fix: can't Create Link larger than balance

apps/daimo-mobile/src/view/screen/AddDeviceScreen.tsx, apps/daimo-mobile/src/view/screen/DeviceScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/shared/ButtonWithStatus.tsx
=> fix: android layout

apps/daimo-mobile/app.json
**Fixed Android layout, other bugfixes and interface improvements.**
Fixed #188 #198 #199 #209 
=> release 0.1.0 build 38

apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/contract/noteIndexer.ts, packages/daimo-api/src/pushNotifier.ts, packages/daimo-api/src/server.ts, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/model.ts
=> feat: notify on note claimed, note redeemed

apps/daimo-mobile/src/action/key.ts, apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/action/useExistingAccount.ts, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/logic/enclave.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/view/screen/AddDeviceScreen.tsx, apps/daimo-mobile/src/view/screen/DeviceScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/test/account.test.ts, packages/daimo-common/src/key.ts, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/BiometricsKeyManager.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/ExpoEnclaveModule.kt, packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift, packages/daimo-expo-enclave/src/index.ts
New step flow:
Closes #215 : Both YT's and Lev's issue should be dealt with now.
=> android: add onboarding step to resolve key issues

apps/daimo-mobile/app.json, apps/daimo-mobile/package.json, apps/daimo-testbed/package.json, apps/daimo-web/package.json, apps/scratchpad/package.json, package-lock.json, package.json
**Better notifications, works on older Androids, bugfixes.**
TODO: screenshot
=> release 0.2.0 build 42

.github/workflows/ci.yml
[do not merge]
Just for tracking diff over master in one place for now.
=> Veridise Audit Fixes

packages/daimo-userop/src/index.ts
=> userop: delete outdated comment

packages/daimo-expo-enclave/ios/FallbackKeyManager.swift, packages/daimo-expo-enclave/ios/SecureEnclaveKeyManager.swift
=> expo-enclave: use guard instead of if nil

packages/daimo-userop/src/daimoOpSender.ts
=> doc: document DaimoOpSender assumptions

apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/pushNotifier.ts, packages/daimo-userop/src/nonce.ts, packages/daimo-userop/test/nonce.test.ts
Fixes Veridise Audit ID 23, tested request tracking still work.
=> fix: check nonceType in DaimoNonceMetadata.fromHex

apps/scratchpad/src/createAccount.ts, apps/scratchpad/src/index.ts, package-lock.json, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-common/src/time.ts
```
cd app/scratchpad
npm start metrics
```
```
[METRICS] using Base Goerli
[METRICS] compiling signups 0xF64840839FdcEDcF70f7C65D6cf4E2558d854ba4
[METRICS] compiling USDC transfers 0x1B85deDe8178E18CdE599B4C9d913534553C3dBf
date,signups,transfers
2023-09-10,1,4
2023-09-17,4,37
2023-09-24,9,40
Done
```
=> feat: scratchpad metrics

apps/daimo-mobile/src/logic/linkStatus.ts, apps/daimo-mobile/src/logic/note.ts, apps/daimo-mobile/src/sync/recipients.ts, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/receive/CreateRequestScreen.tsx, apps/daimo-mobile/src/view/screen/receive/SendRequestScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendScreen.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, packages/daimo-api/src/router.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/daimoLinkStatus.ts, packages/daimo-common/src/model.ts, packages/daimo-common/test/daimoLink.test.ts
Completes half of #262 
- will do base58 encoding separately (surprisingly hard to find a clean package for that)
=> shorten links by using EAccounts when available

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-testbed/App.tsx, packages/daimo-expo-enclave/android/build.gradle, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/Android30PlusKeyManager.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/ExpoEnclaveModule.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/FallbackKeyManager.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/KeyManager.kt, packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift, packages/daimo-expo-enclave/src/index.ts
In line with future plans for #288
=> BiometricsKeyManager > Android30PlusKeyManager, add auth for android 28-29

apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/action/useExistingAccount.ts, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/test/account.test.ts, apps/daimo-testbed/App.tsx, apps/scratchpad/src/createAccount.ts, packages/daimo-api/src/contract/paymaster.ts, packages/daimo-common/src/paymaster.ts, packages/daimo-userop/src/daimoOpBuilder.ts
todo: rebase post audit-1-fix merge
=> display fee estimate from paymaster

apps/daimo-mobile/src/view/screen/SettingsScreen.tsx
https://github.com/daimo-eth/daimo/assets/6984346/e9d299b3-761c-44fd-8b84-c00a642205fe
tested android also
=> fix settings page scroll

apps/daimo-mobile/src/action/key.ts, apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/action/useExistingAccount.ts, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/logic/enclave.ts, apps/daimo-mobile/src/logic/log.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/view/screen/DeviceScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/test/account.test.ts, apps/daimo-testbed/App.tsx, packages/daimo-common/src/key.ts, packages/daimo-expo-enclave/README.md, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/Android30PlusKeyManager.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/ExpoEnclaveModule.kt, packages/daimo-expo-enclave/android/src/main/java/expo/modules/enclave/FallbackKeyManager.kt, packages/daimo-expo-enclave/ios/ExpoEnclaveModule.swift, packages/daimo-expo-enclave/ios/KeyManager.swift, packages/daimo-expo-enclave/ios/KeyStoreError.swift, packages/daimo-expo-enclave/src/index.ts
=> expo-enclave: error bubbling to user, small bug fixes

apps/daimo-mobile/app.json, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, packages/daimo-api/src/contract/nameRegistry.ts
=> release: 0.3.2 build 48

apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteTab.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, packages/daimo-api/src/contract/noteIndexer.ts, packages/daimo-api/src/router.ts, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/daimoLinkStatus.ts, packages/daimo-common/test/daimoLink.test.ts
Works while still pending, before the EphemeralNode exists onchain
=> feat: Payment Link works immediately

packages/daimo-userop/src/daimoOpBuilder.ts
Before:
https://github.com/daimo-eth/daimo/assets/6984346/1cad5000-3942-411d-b254-2a165d0af46b
After:
https://github.com/daimo-eth/daimo/assets/6984346/46a0c9be-76ab-4f0c-9905-a378d857119a
=> userop: remove gas estimation call, speedup 2x

apps/daimo-mobile/app.json
=> release: 0.4.0 build 49

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/SendRequestScreen.tsx, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/router.ts
Fixes bug where repeating the same transaction in a few minutes makes it disappear.
=> never mutate react state, match userops correctly

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/scratchpad/src/index.ts, packages/daimo-api/src/contract/coinIndexer.ts, packages/daimo-api/src/contract/faucet.ts, packages/daimo-api/src/pushNotifier.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/op.ts
Closes #298 
Based on #318 , merge after that.
=> Add paymaster fees to ops display

apps/daimo-mobile/package.json, apps/daimo-mobile/src/logic/trpc.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/OnrampCBPay.tsx, package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/api/getLinkStatus.ts, packages/daimo-api/src/api/search.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/telemetry.ts, packages/daimo-api/src/trpc.ts
=> mobile: add Coinbase Pay onramp

apps/daimo-mobile/app.json
from app review
rainbow's app permissions strings here: https://github.com/rainbow-me/rainbow/blob/af45d85d0f791440e183c18c63fb52a50d424fd0/ios/Rainbow/Info.plist#L191
=> Make permission strings more descriptive

apps/daimo-mobile/app.json, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/shared/AccountBubble.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/style.ts
**App design and mainnet release.**
=> release 1.0.1 build 59

package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/cron.ts, packages/daimo-api/src/router.ts, packages/daimo-api/src/server.ts, packages/daimo-api/src/telemetry.ts
=> api: improved alerts + crontab

.github/PULL_REQUEST_TEMPLATE/release.md, apps/daimo-mobile/app.json, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/vendor/SwipeUpDown.tsx, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/OnrampCBPay.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendNavScreen.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/shared/Badge.tsx, apps/daimo-mobile/src/view/shared/InfoBubble.tsx, packages/daimo-api/src/api/search.ts
=> release: 1.0.4

apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/action/useExistingAccount.ts, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/AddDeviceScreen.tsx, apps/daimo-mobile/src/view/screen/DeviceScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/PendingDot.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/test/account.test.ts, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-common/src/op.ts
devices show as pending if added or removed until next sync:
=> Pending key rotation display, slight send async cleanup

apps/daimo-mobile/app.json, apps/daimo-mobile/package.json, apps/daimo-mobile/src/view/screen/QRScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/OnrampCBPay.tsx, apps/daimo-mobile/src/view/screen/receive/WithdrawScreen.tsx, apps/daimo-mobile/src/view/shared/Check.tsx, apps/daimo-mobile/src/view/shared/SegmentSlider.tsx, apps/daimo-mobile/src/view/shared/style.ts, apps/daimo-mobile/src/view/shared/text.tsx, package-lock.json
CBPay now opens in an external browser.
=> mobile: better deposits screen

apps/daimo-mobile/src/view/shared/AccountBubble.tsx, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-common/src/model.ts
untested because I don't have an account with Coinbase lol
=> create coinbase labelled address

apps/daimo-mobile/src/sync/recipients.ts, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx
=> Display first time box correctly on requests

apps/daimo-web/src/components/AppStoreBadge.tsx, apps/daimo-web/src/components/DownloadLink.tsx, apps/daimo-web/src/utils/platform.ts, packages/daimo-api/src/api/deployWallet.ts
tested pages on android and iOS work
=> web: drop notion form, zuconnect starter devops

apps/daimo-web/src/app/globals.css, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/components/PerformWalletAction.tsx, apps/daimo-web/src/components/buttons.tsx, apps/daimo-web/src/components/typography.tsx, apps/daimo-web/tailwind.config.js
=> Redesign web link and flows

apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx
tested on iOS
based on #383 - will merge after
=> fix first time /account link send bug

apps/daimo-mobile/package.json, apps/daimo-mobile/src/logic/account.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/test/account.test.ts, package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-common/src/model.ts
tested on sim
based on #389 - merge after that
=> move recommended exchanges server side

apps/daimo-mobile/index.js, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-mobile/src/logic/trpc.tsx, apps/daimo-mobile/src/sync/networkState.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/shared/Check.tsx, apps/daimo-mobile/src/view/shared/OfflineHeader.tsx, apps/daimo-mobile/src/view/shared/ScreenHeader.tsx, apps/daimo-mobile/src/view/shared/error.tsx, apps/daimo-mobile/src/view/shared/style.ts, packages/daimo-common/src/func.ts, packages/daimo-common/src/index.ts
=> mobile: add offline indicator

apps/daimo-mobile/src/action/useSendAsync.ts, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/components/PerformWalletAction.tsx
- Say "Pay/Claim with Daimo" instead of just "PAY/CLAIM" in meta tag
- Bubble expo passkeys module errors to user
=> release testing fixes

apps/daimo-web/public/.well-known/assetlinks.json
🤷 android passkey manager works now
=> Add DC's keystore sha

apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/components/PerformWalletAction.tsx, apps/daimo-web/src/components/buttons.tsx
bring back `9af2313` from #401
=> Open in Daimo after first click

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, packages/daimo-api/src/contract/nameRegistry.ts
=> mobile: fix HomeScreen label wrap

apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx
Disable onMount animation for bottom sheet
https://github.com/daimo-eth/daimo/assets/42337257/4c7b4585-bc93-4f35-9df9-328275290985
=> Disable onMount animation for bottom sheet

README.md, apps/daimo-mobile/app.config.js, apps/daimo-mobile/src/sync/recipients.ts, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/WithdrawScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/shared/Amount.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/ScreenHeader.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, apps/daimo-web/src/app/bridge/Widget.tsx, apps/daimo-web/src/utils/rpc.ts, package-lock.json, package.json, packages/daimo-common/src/coin.ts
**Faster, smoother, invite codes, bridge onramp.**
=> release: 1.3.5 build 80

apps/daimo-mobile/src/logic/notify.ts, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, apps/daimo-mobile/src/view/screen/receive/WithdrawScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendNavScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/shared/nav.ts
https://github.com/daimo-eth/daimo/assets/169280/801ff89c-3bc2-4320-b2b2-b48567e90ca0
=> mobile: no autofocus when tabbing

apps/daimo-mobile/src/view/screen/AddDeviceScreen.tsx, apps/daimo-mobile/src/view/screen/AddPasskeyScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx
https://github.com/daimo-eth/daimo/assets/169280/56c552a5-6e8a-46d7-865c-9f954ef14a39
=> mobile: copy account name button

apps/scratchpad/src/index.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/server/server.ts
prevent impersonation
onchain name registry remains permissionless and is unaffected by this change.
this is purely removing a list of names (like fake `vitalik`) from search results and push notifications
=> api: add name blacklist

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/OfflineHeader.tsx
Add flag to remove additional padding when offline banner appear
=> Remove additional padding when offline

apps/daimo-mobile/src/logic/account.ts, apps/daimo-mobile/src/model/account.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/InfoToast.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/test/account.test.ts, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/index.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/test/daimoLink.test.ts
Home screen prompt (only design POC now)
=> add home screen prompt

apps/daimo-mobile/src/sync/recipients.ts, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNavScreen.tsx, apps/daimo-mobile/src/view/shared/nav.ts, packages/daimo-api/src/contract/paymaster.ts
=> release fixes

apps/daimo-web/src/app/link/[[...slug]]/AppOrWalletCTA.tsx, apps/daimo-web/src/app/link/[[...slug]]/CallToAction.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, apps/daimo-web/src/components/buttons.tsx
=> web: open in daimo link

apps/daimo-mobile/src/view/screen/HomeScreen.tsx
=> mobile: remove double content inset

apps/daimo-mobile/app.config.js, apps/daimo-mobile/index.js, apps/daimo-mobile/package.json, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/common/debugLog.ts, apps/daimo-mobile/src/common/useSendDebugLog.ts, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/test/log.test.ts, package-lock.json
Add react-native-share to open debug modal. Works only on physical devices
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/8fb88e23-8ca5-40c1-94c6-eaad432cddfb
Android:
(Coming soon I have to find physical android to test it out)
=> Add debug bottom sheet on shake

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/sync/networkState.ts, apps/daimo-mobile/src/sync/sync.ts
Keep splash screen a little longer waiting for sync or offline banner
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/0ff5a41d-e951-453d-9a40-c933c9755897
Android:
https://github.com/daimo-eth/daimo/assets/42337257/75fe22a6-a5f3-41b1-9fe3-3325768b198d
=> Keep splash screen a little longer waiting for sync

apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/QRScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/AccountCopyLinkButton.tsx, apps/daimo-mobile/src/view/shared/Amount.tsx, apps/daimo-mobile/src/view/shared/ButtonCircle.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, apps/daimo-mobile/src/view/shared/addr.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/style.ts, apps/daimo-mobile/src/view/shared/useSwipeUpDown.tsx, apps/daimo-mobile/test/nav.test.ts, apps/daimo-web/src/app/link/[[...slug]]/AppOrWalletCTA.tsx, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-common/src/eAccount.ts, packages/daimo-common/src/time.ts, packages/daimo-contract/src/chainConfig.ts
https://github.com/daimo-eth/daimo/assets/169280/5234db43-401c-45f1-9a95-5250fc34ad9f
=> AccountScreen

apps/daimo-mobile/src/view/TabNav.tsx
Simple change to change back behaviour on android
Android:
https://github.com/daimo-eth/daimo/assets/42337257/dc172d99-bab2-4512-87aa-d83953b85e32
=> Handle back button tab nav

apps/daimo-mobile/src/view/shared/InputBig.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx, apps/daimo-mobile/src/view/shared/SuggestedActionBox.tsx
To make it more user friendly animate home header and change the layout when input is focused
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/21640003-25d9-478e-9a01-90cc5c4968d5
Android
https://github.com/daimo-eth/daimo/assets/42337257/ce38ac72-e1ff-4353-b50b-7969c5746509
=> Change layout of home screen header after input focus

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/InputBig.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx, apps/daimo-mobile/src/view/shared/SuggestedActionBox.tsx
Fix issues from https://github.com/daimo-eth/daimo/issues/540
=> Remove layout animations for more stable experience

apps/daimo-mobile/src/view/shared/AnimatedSearchInput.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx
Instead of layout animations not it's powered by more reliable animated styles.
Android:
https://github.com/daimo-eth/daimo/assets/42337257/fab8e858-0adc-4a77-9bac-d5e5eecb51bb
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/3ca1ca6a-047e-4746-a24c-22fa9cd3f352
=> Rewrite and restore search header animations

apps/daimo-web/src/app/link/[[...slug]]/CallToAction.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, packages/daimo-api/src/contract/nameRegistry.ts
Cherry pick bug fixes from notev2 branch to release
=> Cherry pick bug fixes to release

apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, packages/daimo-api/src/contract/paymaster.ts
turned it off for testing #552 and forgot to turn it on 😬 
also fixes red CI on master
=> quickfix: turn on sponsoring paymaster and fix master lint

packages/daimo-api/shovel/config.json
tested with shovel-stage instance, will update environment before pushing to prod
Based on #575 , merge that first.
=> shovel: separate mainnet/testnet

apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-web/src/app/link/[[...slug]]/page.tsx, packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-api/test/pushNotifier.test.ts
Closes #571 
Based on #577 , merge that first.
=> payment link: reword claim/reclaim to accept/cancel

apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/shared/AccountCopyLinkButton.tsx, apps/daimo-mobile/src/view/shared/Badge.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/keySlot.ts, packages/daimo-common/test/keySlot.test.ts
=> mobile: SettingsScreen style

packages/daimo-api/src/server/cron.ts
still check some small balance so in case metapaymaster is out of funds we get notified still
=> add metapaymaster check to slack notif

apps/daimo-mobile/package.json, apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/action/useCreateAccount.ts, apps/daimo-mobile/src/logic/invite.ts, apps/daimo-mobile/src/logic/linkStatus.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/InvitePage.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteButton.tsx, apps/daimo-mobile/src/view/shared/IntroTextParagraph.tsx, apps/daimo-web/src/app/link/[[...slug]]/AppOrWalletCTA.tsx, apps/daimo-web/src/app/link/[[...slug]]/CallToAction.tsx, apps/daimo-web/src/components/buttons.tsx, package-lock.json, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/api/getLinkStatus.ts, packages/daimo-api/src/server/router.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/daimoLinkStatus.ts, packages/daimo-common/src/note.ts
https://streamable.com/gjcast
Enables new short payment links.
Starts refactoring code based invites as well.
Closes #497.
Closes #605.
=> auto invite from payment link

apps/daimo-mobile/src/action/key.ts, apps/daimo-mobile/src/view/screen/onboarding/AllowNotificationsPage.tsx, apps/daimo-mobile/src/view/screen/onboarding/CreateAccountPage.tsx, apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx, apps/daimo-mobile/src/view/screen/onboarding/InvitePage.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/UseExistingPage.tsx, apps/daimo-mobile/src/view/shared/InputBig.tsx, packages/daimo-common/src/name.ts
- make subtle button style consistent across pages
- make button position consistent on all pages
- add explainer for usernames
- fix messaging on android key setup page
- fix name validation error message
- fix small screen Use Existing page by reducing whitespace
- refactor shared style to be more minimal
- remove flow selection page / shorten
- don't suggest spellcheck bar on iOS keyboard
Tested on iOS regular and small screens, and Android regular screen size.
Video from iOS large and small: https://streamable.com/6637yt
=> Onboarding design improvements

apps/daimo-mobile/src/view/screen/onboarding/IntroPages.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/UseExistingPage.tsx
Protect users from deleting app and losing money.
Video: https://streamable.com/cdf6lc
=> mobile: move use existing poll to intro page

packages/daimo-api/src/contract/noteIndexer.ts
fixes https://github.com/daimo-eth/daimo/issues/623
=> hotfix: api: handle dupe NoteCreated/Redeemed

apps/daimo-mobile/android-deeplink-config-plugin.js, apps/daimo-mobile/app.config.js, apps/daimo-mobile/package.json, apps/daimo-mobile/src/sync/recipients.ts, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, apps/daimo-mobile/src/view/screen/send/NoteActionButton.tsx, apps/daimo-mobile/src/view/screen/send/RecipientDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/AccountBubble.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx, apps/daimo-mobile/src/view/shared/composeSend.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/shareSheetURL.tsx, apps/daimo-mobile/src/view/shared/shareURL.tsx, package-lock.json, packages/daimo-common/src/model.ts
Tested on iOS and Android, only works on real devices: https://streamable.com/wlj0zb
TODO:
=> mobile: compose payment links to sms/email

apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/server/router.ts
tested locally by switching APIs to Base Goerli and running old client
=> make invite code success backwards compatible

apps/daimo-mobile/src/view/screen/HomeScreen.tsx
Prevent scroll top on home page on iOS
Closes #616
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/b669aad8-4abb-4c8a-b3ad-f607a5ff5b2b
Android:
https://github.com/daimo-eth/daimo/assets/42337257/ad7bb3ea-5830-4f90-9ce8-93adc9f77429
=> Prevent one direction of overscroll on home screen

packages/daimo-api/src/server/trpc.ts
- Noticed a tiny bug while I was poking around your code :)
=> Fix duplicate type

apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/Amount.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/ScreenHeader.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/useSwipeUpDown.tsx
Move HistoryOp screen inside bottom heet on home screen
Closes #553
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/39eb4a5a-a4b7-43c5-9999-c6dd2534272c
Android:
https://github.com/daimo-eth/daimo/assets/42337257/e6993ea3-6540-41eb-92a4-341a978ffedc
=> Move HistoryOp inside bottom sheet

apps/daimo-mobile/src/view/screen/send/RecipientDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SearchResults.tsx
=> mobile: display system contact recipient subtitle

apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/send/SearchResults.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx
=> mobile: fix HomeScreen search

apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx
=> mobile: Request Tab infobox

apps/daimo-mobile/app.config.js, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, apps/daimo-mobile/src/view/screen/send/RecipientDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SearchResults.tsx, apps/daimo-mobile/src/view/screen/send/SearchTab.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, apps/daimo-mobile/src/view/shared/composeSend.tsx
=> release: 1.5.0

apps/daimo-mobile/app.config.js, apps/daimo-mobile/src/view/shared/composeSend.tsx
- fixes android SMS and email popups on many android devices: tried on ~6 devices on simulator, works very consistently
- fixes gmail rendering email in one line by using `\r\n` for new line
=> payment link compose: fix android and non-native iOS mail bug

apps/daimo-mobile/app.config.js
=> release 1.5.2

apps/daimo-mobile/src/view/screen/QRScreen.tsx
https://github.com/daimo-eth/daimo/assets/6984346/dd18a4af-27d0-4c2b-89f6-6a06c2aa928c
=> mobile: scan address QRs

apps/daimo-mobile/src/view/screen/AccountScreen.tsx
This week I trolled and broke account screen a little while fixing the bottom sheet on macOS. I fix it here 😳
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/b501aea9-9ea9-4db7-a27b-f2209eae90c9
macos:
https://github.com/daimo-eth/daimo/assets/42337257/1fdf9a16-11e1-417b-b1aa-a0537b344220
Android:
https://github.com/daimo-eth/daimo/assets/42337257/ee5b59bb-6530-4d7c-9a3f-b81217b8b84e
=> Adjust paddings to make bottom sheet full screen

apps/daimo-mobile/package.json, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/ErrorScreen.tsx, apps/daimo-mobile/src/view/screen/QRScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/error.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-web/src/utils/platform.ts, package-lock.json, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-common/src/appStoreLinks.ts, packages/daimo-common/src/index.ts
It should handle broken deeplinks - both in screens and if link is utterly broken using bottom sheet.
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/22b7aea7-6f39-4d74-98c3-57d9886ff937
Android:
https://github.com/daimo-eth/daimo/assets/42337257/f49b678a-93fe-42de-9e94-f3ff7c7a804d
=> Handle not working deeplinks

apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-contract/src/chainConfig.ts
**Can finally send Sepolia USDC in local testing.**
=> api: fix sepolia Pimlico USDC paymaster

apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, packages/daimo-expo-passkeys/package.json
https://daimo-web-stage-git-dc-fix-daimo.vercel.app/
cc @nalinbhardwaj for post review
=> ci: fix vercel deployment

apps/daimo-mobile/src/view/screen/onboarding/OnboardingScreen.tsx
my bad, didn't look carefully at the review comment https://github.com/daimo-eth/daimo/pull/708#discussion_r1487264088 and just copy pasted
=> onboarding: quickfix review comment previous PR

apps/daimo-mobile/src/view/screen/AddPasskeyScreen.tsx
=> mobile: handle cancel create passkey

apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, apps/daimo-mobile/src/view/shared/nav.ts, apps/daimo-mobile/src/view/shared/useSwipeUpDown.tsx
tested on iOS
closes https://github.com/daimo-eth/daimo/issues/717
=> refactor swipe up/down 

apps/daimo-mobile/app.config.js
=> release: 1.5.4

apps/daimo-web/public/robots.txt, apps/daimo-web/src/app/[...topLevelPage]/route.tsx
@nalinbhardwaj 
fixes https://daimo.com/open-roles etc
=> web: fix super.so proxy, rewrite /_next/

apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-common/src/model.ts
=> mobile: make deposit page copy more explicit

apps/daimo-mobile/app.config.js, apps/daimo-mobile/package.json, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-mobile/src/view/shared/composeSend.tsx, package-lock.json
Closes #754 
Closes #644 
Tested on real iOS and Android device, but didn't record video.
=> mobile email send: multiplex email clients

apps/daimo-mobile/src/view/screen/send/RecipientDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-web/src/app/l/[[...slug]]/page.tsx, apps/daimo-web/src/app/pos/PointOfSalePage.tsx, apps/daimo-web/src/app/pos/page.tsx, packages/daimo-api/src/api/createRequestSponsored.ts, packages/daimo-api/src/api/getLinkStatus.ts, packages/daimo-api/src/api/tagRedirect.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/utils/retryBackoff.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/model.ts, packages/daimo-common/src/time.ts, packages/daimo-common/test/daimoLink.test.ts
=> web: experimental point-of-sale

apps/daimo-mobile/src/App.tsx
see https://github.com/daimo-eth/daimo/issues/665#issuecomment-1962882921
=> mobile: fix freeze on cancelled bottomsheet

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/action/dispatch.ts, apps/daimo-mobile/src/profile/farcaster.ts, apps/daimo-mobile/src/view/sheet/FarcasterBottomSheet.tsx
* disable swipe to dismiss. user must finish connecting or affirmatively cancel.
* fix polling
fixes #771
=> mobile: link farcaster disable swipe to dismiss

apps/daimo-web/src/app/pos/PointOfSalePage.tsx, apps/daimo-web/src/app/pos/page.tsx
=> web: tighter POS

.github/workflows/ci.yml, packages/daimo-api/src/server/cron.ts, packages/daimo-contract/src/index.ts
=> alerts: faucet USDC balance

apps/daimo-mobile/app.config.ts, package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/offchain/inviteCodeTracker.ts, packages/daimo-api/src/server/appVersion.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/src/server/trpc.ts
=> api: Upgrade Available CTA

apps/daimo-mobile/src/view/shared/FarcasterBubble.tsx, packages/daimo-api/src/contract/nameRegistry.ts
=> mobile: fix farcaster in search results

packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-contract/src/index.ts
cc @nalinbhardwaj for post review
fixes #808 faucet display issue
=> contract: fix faucet address

apps/daimo-mobile/app.config.ts
**Offline header, inviter screens, recents**
=> release: 1.6.3

apps/daimo-mobile/src/view/shared/AnimatedSearchInput.tsx
Remove wacky animations of search input when resize app on macos.
MacOS:
https://github.com/daimo-eth/daimo/assets/42337257/35b46915-d871-4769-a9e9-1077769e13b1
(sorry for MV in background 🫠)
=> Remove wacky animations of search input when resize app on macos

apps/daimo-mobile/src/view/screen/InviteScreen.tsx
=> mobile: show invitees even if no invite code

apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx
checked in sim
https://streamable.com/70i42d
=> payment link: make history op cancel work, make back not cross

apps/daimo-mobile/src/common/nav.ts, apps/daimo-mobile/src/logic/key.ts, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingEnterInviteScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingIntroScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingPickNameScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingSetupKeyPage.tsx
=> mobile: OnboardingSetupKeyPage

apps/daimo-mobile/src/view/screen/receive/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/receive/WithdrawScreen.tsx
Closes #825
Move padding inside scrollviews
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/443e7eca-8b70-472d-b099-5beeda1a3a16
=> Move padding inside scrollviews

apps/daimo-mobile/src/logic/passkey.ts
Recreated it once on a handful of attempts, might as well bump this up to try to fix.
=> Passkey: Bump up retyBackoff trials

apps/daimo-mobile/src/App.tsx, apps/daimo-mobile/src/common/nav.ts, apps/daimo-mobile/src/logic/accountManager.ts, apps/daimo-mobile/src/logic/deeplink.ts, apps/daimo-mobile/src/logic/linkStatus.ts, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/AccountScreen.tsx, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingEnterInviteScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingIntroScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingPickNameScreen.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingUseExistingScreen.tsx, packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/offchain/inviteCodeTracker.ts, packages/daimo-api/src/server/router.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/invite.ts
=> mobile: fix onboarding

apps/daimo-mobile/src/App.tsx
Closes #768
Just close keyboard before open debug modal
=> Dismiss keyboard when show debug modal

packages/daimo-api/src/shovel/watcher.ts
Note:
```
2024-03-22 06:34:24.875 [daimo_render] [INFO] daimo-api-prod web-bp82z 1 [SHOVEL] loading 12162557 to 12162558
2024-03-22 06:34:27.836 [daimo_render] [INFO] daimo-api-prod web-bp82z 1 [SHOVEL] loading 12162557 to 12162560
```
=> shovel: fix parallel conflicting execution

packages/daimo-api/src/api/sendUserOpV2.ts, packages/daimo-api/src/env.ts, packages/daimo-api/src/network/bundlerClient.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/server/cron.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/test/dtest.ts
Closes #891 
^purposefully broke signatures sent by client
=> telemetry: log reverted txes, increase paymaster warns

packages/daimo-api/src/contract/paymaster.ts, packages/daimo-api/src/network/bundlerClient.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/offchain/inviteCodeTracker.ts, packages/daimo-api/src/server/cron.ts, packages/daimo-api/src/server/server.ts
Fixes potential nonce out of syncs
=> api: send transactions ourselves

apps/daimo-mobile/src/common/nav.ts, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/InviteScreen.tsx, apps/daimo-mobile/src/view/screen/YourInvitesScreen.tsx
simple your invites screen, closes #903
=> Invite tab: Your invites screen

packages/daimo-api/src/api/deployWallet.ts, packages/daimo-api/src/contract/coinIndexer.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/network/bundlerClient.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/utils/retryBackoff.ts
CC @nalinbhardwaj for post review.
* Fix connection exhaustion
* Fix `retryWithBackoff`. Before, it would retry for ~10 minutes by default (!) Now, 10s.
=> api: remove unused estimatePreVerGas, fix connection exhaustion

apps/daimo-mobile/app.config.ts
Closes first part of #909
Android:
https://github.com/daimo-eth/daimo/assets/42337257/6c34f557-50d5-4337-8bec-86b9c3fa644a
=> Remove gradient from icon to fix splash screen

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/shared/AnimatedSearchInput.tsx, apps/daimo-mobile/src/view/shared/SearchHeader.tsx, apps/daimo-mobile/src/view/shared/SearchResults.tsx
Close #829 together with #884
Sorry about android bug, I missused styles in wrong component 🫠
Android:
https://github.com/daimo-eth/daimo/assets/42337257/46fc493d-17fd-4856-accf-dfba3a66a554
iOS:
https://github.com/daimo-eth/daimo/assets/42337257/7a33bf02-3b40-4da4-96ec-043f59e0ff28
=> Don't close search when accidentally dismiss keyboard (and don't break android along the way)

apps/daimo-mobile/src/logic/accountManager.ts, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/send/MemoDisplay.tsx, apps/daimo-mobile/src/view/shared/Button.tsx
=> mobile: HistoryOpScreen help button

apps/daimo-mobile/app.config.ts, apps/daimo-mobile/src/view/screen/HistoryOpScreen.tsx, apps/daimo-mobile/src/view/shared/HistoryList.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, apps/daimo-mobile/src/view/sheet/OwnRequestBottomSheet.tsx
=> release: design fixes

apps/daimo-mobile/src/action/dispatch.ts, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-mobile/src/view/shared/Button.tsx, apps/daimo-mobile/src/view/shared/InfoBox.tsx, apps/daimo-mobile/src/view/shared/InfoLink.tsx, packages/daimo-api/src/api/getAccountHistory.ts
=> mobile: explain payment links

apps/daimo-mobile/src/view/screen/HomeScreen.tsx
=> android: disable checklist box shadow

packages/daimo-api/src/server/server.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/test/dtest.ts
I think this fixes memo display?
=> api: fix indexer ordering

apps/daimo-mobile/src/logic/daimoContacts.ts, apps/daimo-mobile/src/logic/log.ts, apps/daimo-mobile/src/logic/passkey.ts, apps/daimo-mobile/src/view/shared/SearchResults.tsx
- make AASA bug error more helpful
- fix last send / receive population in contact, closes #967 
tested by running a couple phones side by side and trying a few combinations
=> release fixes 1.8.1

apps/daimo-mobile/app.config.ts
**Deposit tab. Invite frame.**
=> release: 1.8.2

apps/daimo-mobile/app.config.ts
**Fixes exit button**
Short checklist, no phone.
Use Android simulator.
**Opening send flow from Home tab, then clicking back a few times, drops you on the Send tab.** This is existing behavior, but may be worth revisiting in future.
Ran into https://github.com/daimo-eth/daimo/issues/978 , worked on second try.
=> release v1.8.3

apps/daimo-mobile/app.config.ts, apps/daimo-mobile/src/view/screen/onboarding/OnboardingFinishScreen.tsx
**Onboarding improvements.**
**Abbreviated checklist. No changes other than onboarding.**
=> release: 1.8.4

package-lock.json, packages/daimo-api/.gitignore, packages/daimo-api/.sample-env, packages/daimo-api/package.json, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/telemetry.ts, packages/daimo-api/tsconfig.json
This PR adds Sentry error reporting to the daimo api.
=> Add Sentry error reporting

apps/daimo-mobile/src/view/screen/InviteScreen.tsx, apps/daimo-mobile/src/view/shared/AnimatedSearchInput.tsx, apps/daimo-mobile/src/view/shared/InputBig.tsx, apps/daimo-mobile/src/view/shared/PressableText.tsx, apps/daimo-mobile/src/view/shared/SearchScreen.tsx
This PR adds a cancel button the search inputs on the send/request screens, and left-aligns the search icons on send, request and home screens.
| Home | Send | Request |
| ------ | ----- | -------- |
| ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 07 20 35](https://github.com/daimo-eth/daimo/assets/15985212/55124898-994e-4157-a4da-d07323b475e5) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 07 21 02](https://github.com/daimo-eth/daimo/assets/15985212/b5bc3404-0f60-4520-aec5-7b33a5867c41) | ![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-09 at 07 21 33](https://github.com/daimo-eth/daimo/assets/15985212/ed9fd606-3738-4dd5-b290-21509ed8d71f) |
=> Add cancel button to search inputs

apps/daimo-mobile/src/view/sheet/GlobalBottomSheet.tsx
=> mobile: disable farcaster connect sheet click dismiss

.github/workflows/ci.yml, apps/daimo-mobile/.maestro/upload-build.sh
=> mobile: fix EAS prod CI build

packages/daimo-api/src/api/search.ts, packages/daimo-api/src/contract/coinIndexer.ts, packages/daimo-api/src/contract/keyRegistry.ts, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/contract/requestIndexer.ts, packages/daimo-api/src/shovel/watcher.ts
=> api: dedupe search results

apps/daimo-mobile/app.config.ts
**Back up your account offline, using a seed phrase or Yubikey.**
=> release: 1.8.5

apps/daimo-web/src/components/Header.tsx
=> fix: fix links

packages/daimo-api/src/contract/ethIndexer.ts, packages/daimo-api/src/server/cron.ts, packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-common/src/model.ts
=> api: reduce ethIndexer load even more

apps/daimo-mobile/src/logic/inAppNotifications.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/notifications/SwapNotificationRow.tsx, apps/daimo-mobile/src/view/sheet/SwapBottomSheet.tsx, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/contract/ethIndexer.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/network/uniswapClient.ts, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/model.ts
tested on local prod API with sim -- sends push notifs still, shows getAccountHistory fast
=> getAccountHistory: don't wait for uniswap

apps/daimo-mobile/src/view/screen/history/HistoryOpScreen.tsx, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-common/src/model.ts
=> mobile: li.fi label, "no fees" display

apps/daimo-mobile/src/view/screen/history/shared.ts, apps/daimo-mobile/src/view/shared/Bubble.tsx, apps/daimo-mobile/src/view/shared/Button.tsx
=> mobile: cleanup

packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/server/coinList.ts, packages/daimo-common/src/foreignCoin.ts
tested on local sim with prod API
=> quickfix push notifier: don't send push notifs on dust

apps/daimo-mobile/src/view/screen/link/NoteScreen.tsx, packages/daimo-api/src/api/getLinkStatus.ts, packages/daimo-api/src/network/uniswapClient.ts
=> mobile: display pending payment links

apps/daimo-mobile/src/view/screen/history/HistoryOpScreen.tsx
=> mobile: link to ethreceipts

packages/daimo-api/src/contract/ethIndexer.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/contract/homeCoinIndexer.ts, packages/daimo-api/src/contract/indexer.ts, packages/daimo-api/src/contract/keyRegistry.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/contract/noteIndexer.ts, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/contract/requestIndexer.ts, packages/daimo-api/src/shovel/watcher.ts
Fixes following error
```
[API] serving GET /chain/8453/health
at async Watcher.init (/opt/render/project/src/packages/daimo-api/src/shovel/watcher.ts:95:5)
at async Watcher.catchUpTo (/opt/render/project/src/packages/daimo-api/src/shovel/watcher.ts:131:21)
at async Watcher.index (/opt/render/project/src/packages/daimo-api/src/shovel/watcher.ts:146:7)
at async Promise.all (index 2)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at ForeignCoinIndexer.load (/opt/render/project/src/packages/daimo-api/src/contract/foreignCoinIndexer.ts:89:16)
at ForeignCoinIndexer.processSwapCoinLogs (/opt/render/project/src/packages/daimo-api/src/contract/foreignCoinIndexer.ts:95:12)
at ForeignCoinIndexer.processSwapCoinDelta (/opt/render/project/src/packages/daimo-api/src/contract/fore …
```
=> hotfix: api: handle missing transfers

.dockerignore, packages/daimo-api/Dockerfile
=> api: fix docker build

apps/daimo-mobile/src/view/shared/AmountInput.tsx
=> mobile: currency switcher centring, hitbox

apps/daimo-clippy/package.json, apps/daimo-clippy/src/handlers.ts, apps/daimo-clippy/src/index.ts, packages/daimo-api/src/server/telemetry.ts
Usage: `@clippy grant user=alice` + optional ` dollars=7`, default $10.
=> clippy: add grant command

apps/daimo-mobile/src/view/screen/HomeScreen.tsx
=> mobile: down arrow icon for request

apps/daimo-mobile/src/view/screen/DepositScreen.tsx, apps/daimo-mobile/src/view/sheet/DepositAddressBottomSheet.tsx
=> mobile: fix Deposit copy

.github/workflows/maestro-ci.yml, apps/daimo-mobile/app.config.ts
**More currencies, nicer icons, better deposit page.**
=> release: 1.8.9

packages/daimo-api/src/contract/nameRegistry.ts
=> api: load ENS names once

apps/daimo-mobile/src/logic/decodeQR.ts, apps/daimo-mobile/src/view/screen/QRScreen.tsx, apps/daimo-mobile/test/decodeQR.test.ts
=> mobile: scan CB QRs

apps/daimo-mobile/app.config.ts
**Support scanning all major wallet QR codes.**
=> release: 1.8.10

.vscode/launch.json, packages/daimo-api/package.json, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/server/server.ts
add VSCode launch configuration to debug daimo-api
workaround Viem error-printing bug
=> api: fix Viem transactions

apps/daimo-mobile/src/view/screen/history/shared.ts, apps/daimo-mobile/src/view/screen/notifications/RequestNotificationRow.tsx, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/scratchpad/src/index.ts, package-lock.json, packages/daimo-api/src/api/createRequestSponsored.ts, packages/daimo-api/src/contract/requestIndexer.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/test/dtest.ts, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/daimoLinkStatus.ts
=> mobile, api: add request memos

README.md, apps/daimo-clippy/.env.example, apps/daimo-mobile/eas.json, apps/daimo-web/package.json, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/server/node.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/test/dtest.ts
=> api: more detailed /health check

apps/daimo-mobile/src/logic/inAppNotifications.ts, apps/daimo-mobile/src/sync/sync.ts, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, apps/daimo-mobile/src/view/sheet/OwnRequestBottomSheet.tsx, packages/daimo-api/src/server/pushNotifier.ts
=> api: add request-created push notification

.github/PULL_REQUEST_TEMPLATE/release.md, apps/daimo-mobile/app.config.ts
**Link memos, Deposit from Binance.**
=> release: 1.9.0

apps/daimo-mobile/src/logic/trpc.tsx, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, packages/daimo-api/src/api/createRequestSponsored.ts, packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-api/src/server/router.ts, packages/daimo-common/src/request.ts
Simplify frontend, make create-req push notifs instant
=> api: send create-request push immediately

packages/daimo-api/src/contract/requestIndexer.ts
https://github.com/daimo-eth/daimo/issues/1160
=> api: hotfix requestIndexer

.eslintrc, apps/scratchpad/src/createAccount.ts, apps/scratchpad/src/index.ts, package-lock.json, packages/daimo-api/package.json, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/api/getExchangeRates.ts, packages/daimo-api/src/api/healthCheck.ts, packages/daimo-api/src/api/search.ts, packages/daimo-api/src/codegen/dbApi.ts, packages/daimo-api/src/codegen/dbShovel.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/db/externalApiCache.ts, packages/daimo-api/src/network/binanceClient.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/server.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/src/utils/retryBackoff.ts, packages/daimo-api/test/dtest.ts, packages/daimo-contract/src/shovel/config.json, packages/daimo-contract/src/shovel/ethTransfers.ts, packages/daimo-contract/src/shovel/index.ts
- New `external_api_cache`
- Lots more logging
- Turn off `eth_transfers` in Shovel. This was the proximate cause of #1164 
cc @kayleegeorge
=> api, shovel: hotfix. turn off eth_transfers, add caching, add logging

packages/daimo-api/src/api/getAccountHistory.ts
they made a new page just for us
=> upgrade relay bridge link

apps/daimo-clippy/src/handlers.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/server/router.ts
Add a "disable bonus" for invite link feature for clippy. Invite link still remains valid, but the bonus is set to 0.
=> clippy: add "disable bonus" command

packages/daimo-api/src/db/db.ts
Fixes update invite code clippy command.
=> clippy: small fix to update link

packages/daimo-contract/src/shovel/Dockerfile, packages/daimo-contract/src/shovel/config.json
cc @nalinbhardwaj 
testing in prod tonight, will revert if it causes issues
=> shovel: eth_transfers, smaller batch, lower db load

packages/daimo-contract/src/shovel/config.json, packages/daimo-contract/src/shovel/index.ts
confirm that this solves the "no logs for block" issue
=> shovel: disable eth_transfers in stage

packages/daimo-api/src/api/validateMemo.ts
=> api: fix memo validator

apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, packages/daimo-api/src/api/getSwapRoute.ts, packages/daimo-api/test/basics.test.ts, packages/daimo-api/test/dtest.ts, packages/daimo-common/src/chain.ts, packages/daimo-common/src/foreignToken.ts
Add chain and foreign token constants for account upgrade. 
Fix: Prevent send any-stable on testnet (no swapper / Uniswap pools).
=> common: add chain and token information

.github/workflows/cd.yml
https://github.com/daimo-eth/daimo/issues/1188
=> CD: Publish APK to Github release

packages/daimo-api/src/db/db.ts
typo in UpdateInviteCodeArgs: `bonusDollarInviter` instead of `bonusDollarsInviter` --> causing invite link args to not update properly
=> clippy: fix typo

apps/daimo-web/src/app/pos/PointOfSalePage.tsx, apps/daimo-web/src/app/pos/page.tsx, apps/daimo-web/src/components/typography.tsx
=> web: last minute eu pos

packages/daimo-api/src/codegen/dbApi.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-api/src/server/router.ts, packages/daimo-api/src/server/trpc.ts, packages/daimo-api/src/shovel/watcher.ts, packages/daimo-api/test/pushNotifier.test.ts, packages/daimo-common/src/model.ts
=> api: dont double-notify

apps/daimo-mobile/test/assets/accountDcposchV15.json, packages/daimo-api/src/api/getAccountHistory.ts
They're moving the URL -- tested on sim
=> api: change relay.link URL

apps/daimo-mobile/src/view/screen/onboarding/OnboardingChooseNameScreen.tsx, packages/daimo-common/src/name.ts
- auto lowercase input in username field
- show "must start with lowercase letter" before "too short"
=> onboarding name: lowercase, show starting error first

apps/daimo-clippy/src/handlers.ts
I need to telegram them the link separately from time to time
=> slackbot: put invite link in response

packages/daimo-common/src/currencies.ts
Adding new currency New Taiwan Dollar (NT$)
=> api: add currency TWD

apps/daimo-mobile/src/action/actStatus.ts, apps/daimo-web/src/app/pos/page.tsx, packages/daimo-api/Dockerfile, packages/daimo-api/src/api/getAccountHistory.ts, packages/daimo-api/src/api/healthCheck.ts, packages/daimo-api/src/contract/SwapClogMatcher.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/contract/homeCoinIndexer.ts, packages/daimo-api/src/contract/indexer.ts, packages/daimo-api/src/contract/keyRegistry.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/contract/noteIndexer.ts, packages/daimo-api/src/contract/opIndexer.ts, packages/daimo-api/src/contract/requestIndexer.ts, packages/daimo-api/src/db/db.ts, packages/daimo-api/src/network/bundlerClient.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/shovel/watcher.ts
- Speed up OpIndexer
- ForeignCoinIndexer runs smoothly with no materialized views now
- Health check monitors indexers
Startup still slower than I'd like, 8 minutes:
=> api: health check, faster indexers

apps/daimo-mobile/src/common/featureFlag.ts, apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/screen/DepositScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, packages/daimo-common/src/i18n/languages/en.ts, packages/daimo-common/src/i18n/languages/es.ts
Separately from this PR: fixed `eth_transfers` indexing.
=> mobile: release testing fixes

apps/daimo-mobile/app.config.ts, package-lock.json
**Spanish translation.**
Additional test:
+ Additional tests:
*Not updating prod API for this release. We will follow up with an indexer upgrade. See #1239*
=> release: 1.9.2

apps/daimo-mobile/src/view/screen/send/CoinDisplay.tsx, packages/daimo-api/src/contract/nameRegistry.ts
- add correct address for `instant cross-chain`
- fix coloring nit
=> api: add correct address for instant cross-chain

apps/daimo-mobile/src/common/featureFlag.ts, apps/daimo-mobile/src/view/screen/send/CoinDisplay.tsx, apps/daimo-mobile/src/view/screen/send/RouteDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx
- remove route display for cross-chain, same coin
- remove feature flag
=> mobile: remove feature flag

apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/screen/history/HistoryList.tsx, apps/daimo-mobile/src/view/screen/history/HistoryOpBottomSheet.tsx, apps/daimo-mobile/src/view/screen/onboarding/OnboardingIntroScreen.tsx, apps/daimo-mobile/src/view/shared/SwipeUpDown.tsx, packages/daimo-api/src/api/getExchangeRates.ts, packages/daimo-common/src/chain.ts, packages/daimo-common/src/func.ts
with stub API setting `postSwapTransfer`:
=> mobile: show real chain+coin

apps/daimo-mobile/src/storage/storedTypes.ts, apps/daimo-mobile/src/view/screen/history/HistoryOpBottomSheet.tsx, apps/daimo-mobile/src/view/screen/send/CoinDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, packages/daimo-common/src/i18n/languages/en.ts, packages/daimo-common/src/i18n/languages/es.ts, packages/daimo-common/src/index.ts, packages/daimo-common/src/model.ts, packages/daimo-common/src/op.ts, packages/daimo-common/src/sendPair.ts
- move supportedChains to daimo/common to allow testnet
=> mobile: release nits draft

apps/daimo-mobile/src/i18n/languages/es.ts, packages/daimo-common/src/currencies.ts
=> fix boliviano symbol

README.md, apps/daimo-web/src/i18n/languages/en.ts, apps/daimo-web/src/i18n/languages/es.ts
=> web: fix tagline

packages/daimo-api/src/network/viemClient.ts
=> Revert "API: fix nonce issue"

apps/daimo-mobile/app.config.ts
=> release: 1.9.4

apps/daimo-mobile/app.config.ts
Better support for deeplinks with our tag system.
=> Release 1.9.5

apps/daimo-mobile/src/logic/memo.ts, apps/daimo-mobile/src/view/screen/receive/ReceiveScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendNoteScreen.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, packages/daimo-api/src/api/getAccountHistory.ts
=> mobile: add currency to [pay, req] link memos

apps/daimo-mobile/app.config.ts
Support for tag deeplinks during onboarding
=> release: 1.9.6

apps/daimo-clippy/package.json, apps/daimo-clippy/src/env.ts, apps/daimo-clippy/src/handlers.ts, package-lock.json, packages/daimo-api/src/api/getSwapRoute.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/contract/homeCoinIndexer.ts, packages/daimo-api/src/server/router.ts
- load from daimo_transfers in orders
- correct proposedSwap timestamps
- better logging
=> api: correct proposed swaps

apps/daimo-web/src/app/download/other/page.tsx, apps/daimo-web/src/app/download/route.tsx, apps/daimo-web/src/components/DownloadLink.tsx, apps/daimo-web/src/components/buttons.tsx, apps/daimo-web/src/i18n/languages/en.ts, apps/daimo-web/src/i18n/languages/es.ts, apps/daimo-web/src/utils/platform.ts
Created a getter function for  to reflect i18n and small change download page to add a word to i18n
=> web: i18n for download links

apps/daimo-mobile/src/common/nav.ts
=> mobile: handle invalid links in onboarding / Accept Invite

apps/daimo-clippy/src/handlers.ts
=> slackbot: add invitees

packages/daimo-api/src/contract/homeCoinIndexer.ts
=> api: filter zero value transfers to prevent app bricking

packages/daimo-common/src/index.ts, packages/daimo-common/src/viemClient.ts
- common functions used for viem client setup
=> common: add viem client common functions

packages/daimo-api/src/db/db.ts
- add `blocks` table
- readd `IndexDB` setup (got deleted in commit https://github.com/daimo-eth/daimo/commit/6ee66925468f77a9f6e8ab88a99691fa8ceb8911)
=> db: add blocks to IndexDB setup

apps/daimo-mobile/src/logic/memo.ts, apps/daimo-mobile/src/view/screen/notifications/RequestNotificationRow.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx
=> mobile: fix fulfilled req links

apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/screen/history/HistoryOpBottomSheet.tsx, packages/daimo-common/src/op.ts
=> mobile: LL: copy + show ETA

apps/daimo-mobile/app.config.ts
**Landline, Bitrefill & better cross-chain sends.**
**Reinstall prod app.** Testing rest of this in prod:
=> release: 1.9.7

apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/screen/SettingsScreen.tsx, apps/daimo-mobile/src/view/screen/keyRotation/DeviceScreen.tsx
=> mobile: make last key setting delete

apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/screen/keyRotation/DeviceScreen.tsx
=> mobile: fix delete account

.github/PULL_REQUEST_TEMPLATE/release.md, apps/daimo-mobile/app.config.ts
**Better display for cross-chain transactions. Delete account button.**
=> release: 1.9.9

packages/daimo-common/src/landline.ts
See https://github.com/daimo-eth/daimo-exchange/pull/15
=> api: handle fast wire+landline transfers

packages/daimo-api/src/api/featureFlag.ts
=> landline: feat flag update

apps/daimo-mobile/src/action/useLandlineDeposit.ts, packages/daimo-api/src/landline/landlineClogMatcher.ts, packages/daimo-api/test/getAccountHistory.test.ts, packages/daimo-common/src/landline.ts, packages/daimo-common/src/op.ts
=> api: Landline pending fast deposits

apps/daimo-mobile/src/logic/swapRoute.ts, apps/daimo-mobile/src/storage/storedTypeMigrations.ts, apps/daimo-mobile/src/storage/storedTypes.ts, apps/daimo-mobile/src/view/screen/notifications/SwapNotificationRow.tsx, apps/daimo-mobile/src/view/screen/send/CoinDisplay.tsx, apps/daimo-mobile/src/view/screen/send/FulfillRequestButton.tsx, apps/daimo-mobile/src/view/screen/send/RouteDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/shared/AmountInput.tsx, apps/daimo-mobile/src/view/sheet/SwapBottomSheet.tsx, packages/daimo-api/src/api/getSwapRoute.ts, packages/daimo-api/src/contract/ClogMatcher.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/server/cron.ts, packages/daimo-api/src/server/pushNotifier.ts, packages/daimo-api/src/server/tokenRegistry.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/src/format.ts, packages/daimo-common/src/op.ts, packages/daimo-common/src/sendPair.ts, packages/daimo-common/test/daimoLink.test.ts, packages/daimo-contract/src/chain.ts, packages/daimo-contract/src/foreignToken.ts, packages/daimo-contract/src/index.ts, packages/daimo-userop/src/daimoOpSender.ts
The swap memo ($x -> Y ETH) doesn't appear while the transaction is pending. We can fix this in a future cleanup refactor.
=> common: add Base ETH send pair, chain/token cleanup

apps/daimo-mobile/src/common/nav.ts, apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/view/screen/LandlineBankTransfer.tsx, apps/daimo-mobile/src/view/screen/send/CoinDisplay.tsx, apps/daimo-mobile/src/view/screen/send/MemoDisplay.tsx, apps/daimo-mobile/src/view/screen/send/RouteDisplay.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferButton.tsx, apps/daimo-mobile/src/view/screen/send/SendTransferScreen.tsx, apps/daimo-mobile/src/view/sheet/BitrefillBottomSheet.tsx, apps/daimo-mobile/test/nav.test.ts, packages/daimo-common/src/daimoLink.ts, packages/daimo-common/test/daimoLink.test.ts
* Enter `ansgar.eth`
* Pick USDC Optimism, enter a few cents
* Click Send to go to the confirm screen
Current behavior on master: confirm screen shows USDC Base
Fixed behavior: confirm screen shows USDC Optimism
=> mobile: fix cross-chain send

apps/daimo-mobile/src/view/screen/HomeScreen.tsx, apps/daimo-mobile/src/view/style/skinCover/index.tsx
=> mobile: hide skins background on search

apps/daimo-mobile/src/i18n/languages/en.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/view/TabNav.tsx, apps/daimo-mobile/src/view/screen/LandlineTransferScreen.tsx
* Fix centering
* Fix copy
* Don't deposit status (eg "funds will arrive instantly") on withdrawal, those take longer
=> mobile: fix LandlineBankTransfer screen

package-lock.json, packages/daimo-api/src/contract/ClogMatcher.ts, packages/daimo-api/src/contract/foreignCoinIndexer.ts, packages/daimo-api/src/contract/homeCoinIndexer.ts, packages/daimo-api/src/contract/nameRegistry.ts, packages/daimo-api/src/contract/noteIndexer.ts, packages/daimo-api/src/contract/requestIndexer.ts, packages/daimo-common/package.json, packages/daimo-common/src/viemClient.ts, packages/daimo-contract/package.json, packages/daimo-contract/script/gen-feeds.ts, packages/daimo-contract/script/gen-tokens.ts, packages/daimo-contract/script/util.ts, packages/daimo-contract/src/index.ts, packages/daimo-userop/src/daimoOpSender.ts
=> api, contract: support old+new DaimoFastCCTP

apps/daimo-web/src/utils/linkStatus.ts
=> web: display request memos

apps/daimo-mobile/src/view/style/skins.ts
- remove skin font for Android (no spicy font support)
fixed:
=> mobile: add default font

packages/daimo-common/src/daimoPay.ts
Step 1: merge contracts into `daimo`
Step 2: move `pay-*` packages into `daimo-internal`, update `daimo` submodule
=> common: DaimoPayOrderMetadata

apps/daimo-mobile/app.config.ts
**Bug fixes and performance improvements**
=> release: 1.9.12

apps/daimo-mobile/src/i18n/index.ts, apps/daimo-mobile/src/i18n/languages/es.ts, apps/daimo-mobile/src/i18n/languages/my.ts
=> mobile app: burmese translation

packages/daimo-api/src/api/claimEphemeralNoteSponsored.ts, packages/daimo-api/src/api/createRequestSponsored.ts, packages/daimo-api/src/contract/accountFactory.ts, packages/daimo-api/src/network/bundlerClient.ts, packages/daimo-api/src/network/viemClient.ts, packages/daimo-api/src/network/viemClientUtils.ts, packages/daimo-api/src/offchain/inviteCodeTracker.ts
add retry logic to viem client to resubmit txs on "nonce too low" errors or gas price related errors
=> api: more reliable viem client
